### ISSUE TITLE
Virus detected in latest commit!!

### ISSUE THREAD

**Issue by omegasrevenge** [TehCheat/PoEHUD#100]
When downloading and opening the PoeHud files from here: http://imgur.com/a/BtrZ3
My AntiVirus gets mad and spits out this: http://imgur.com/a/yxHRl
There seems to be a Trojan Horse in the latest commit!!!

**Comment by DetectiveSquirrel** [comment]
false positive...

**Comment by omegasrevenge** [comment]
How can I check if it is indeed a "false positive?"

**Comment by TehCheat** [comment]
Examine the code, determine if there's anything malicious, compile it yourself if you deem there's nothing malicious.  It reads the memory of another process, of course an antivirus can be triggered.

**Comment by omegasrevenge** [comment]
How do I make my AntiVirus trust the files then? Every single time I try to extract it or restart the program once I have extracted the files it immediately find the false positive and deletes the exe!

**Comment by TehCheat** [comment]
You can usually whitelist a folder.  I'm not familiar with Avira, so I have no idea how.

**Comment by omegasrevenge** [comment]
Found out how, and whitelisted it. Hopefully my computer won't get eaten by a Trojan soon... :P
Thanks for your help.
