### ISSUE TITLE
System.MissingMethodException at IngameUIElements.get_InventoryPanel()

### ISSUE THREAD

**Issue by 0xe0d59** [TehCheat/PoEHUD#103]
This exception breaks the InventoryItemsAnalyzer plugin (https://github.com/k-Sacr/InventoryItemsAnalyzer). Same for Inventory Preview plugin.

**Comment by TehCheat** [comment]
It must have already been broken because I did nothing to change it.

**Comment by 0xe0d59** [comment]
@TehCheat Fiddled a little and as far as I can tell InventoryPanel is created as a Element class object instead of a Inventory object. This causes referencing InventoryPanel to throw the exception, because that object is trying to cast itself to a derived type. For example, explicitly casting InventoryPanel to Element fixes this problem temporarily. 

`!((Element)GameController.Game.IngameState.IngameUi.InventoryPanel).IsVisible`

Can't tell how to fix it, don't know that much about generics.

**Comment by TehCheat** [comment]
You can change it at the root, and it works... for a while.  But I get a crash after a few seconds with it trying to download.  I'll probably remove it from the project and if someone wants to get it working they can.  It's an external plugin, it shouldn't be in the project.

**Comment by 0xe0d59** [comment]
Well yes, the Inventory Preview plugin was broken for a while and shouldn't be in the project in its current state. But there seems to be a problem with the RemoteMemoryObjects, not working with derived classes as shown in the case of InventoryPanel.

**Comment by zaafar** [comment]
@TehCheat  please let me look at the issue before changing/removing it.

**Comment by TehCheat** [comment]
It's an external plugin, it shouldn't be in the main project.  It should be managed separately.

**Comment by zaafar** [comment]
oh....I have fixed the Inventory Preview plugin. It's working fine now. I agree that it's a plugin and shouldn't be in the project anyway. Do whatever u want with it :)

I was talking about element "GameController.Game.IngameState.IngameUi.InventoryPanel" that shouldn't be removed/changed.


@0xe0d59 InventoryPanel is of inventory type, not element type. you don't have to typecast it into (Element) before using IsVisible as inventory type is drive from Element type.

**Comment by 0xe0d59** [comment]
@zaafar Maybe, but casting it removed the problem, the plugin found the isVisible method that way.

**Comment by zaafar** [comment]
Can you link me the plugin where you did the changes?

**Comment by 0xe0d59** [comment]
@zaafar https://github.com/k-Sacr/InventoryItemsAnalyzer

**Comment by TehCheat** [comment]
If you change that line to the following, it should work.

> if (!GameController.Game.IngameState.IngameUi.ReadObjectAt<Element>(0xBD8).IsVisible)
