### ISSUE TITLE
Health bars

### ISSUE THREAD

**Issue by newstlastlist** [TehCheat/PoEHUD#111]
Dont work health bars on players and mobs, But other things work well.
http://imgur.com/a/KGuS3

**Comment by RyuuOujiXS** [comment]
Could this be related to the graphical modification you've made?

**Comment by newstlastlist** [comment]
I have
adapter - nvidia quadro 4000m
display mode - windowed
resolution 1920x1018
VSynq - no
Shadow quality - off
Antialiasing quality - off
texture quality - medium
texture filtering - trilinear
Post processing - off
Screen shake - off
engine multithreading - disabled
directX - 9 Ex

**Comment by TehCheat** [comment]
No one else seems to be having this problem, so I'm closing this.
