### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by Legacylooter** [TehCheat/PoEHUD#112]
The HUD occasionally freezes completely. This includes whatever enemies were on the map at the time as well. Might also be worth noting that when it freezes, you can see the hud even on desktop.
![capture](https://cloud.githubusercontent.com/assets/26748062/24421685/0120f1a8-13c5-11e7-9e83-167b1f2c9d14.PNG)

**Comment by TehCheat** [comment]
This is a problem that has existed all of HUD's existence.  Essentially the overlay can get out of sync with the game and be in the middle of reading something that is moved or no longer exists in memory.  I've found that faster PCs with some kind of frame limiter seems to be the most consistent way to protect against this, but it's not perfect.  My old potato PC would have this problem far more often than my current PC does.

**Comment by RyuuOujiXS** [comment]
A program like RivaTuner can limit your FPS and possibly help in this situation.  Note that 1 FPS is approximately 1 Hz Refresh Rate so 60 Hz is about 60 FPS max.

**Comment by TehCheat** [comment]
A change was made to fix this.  Let me know if it's still freezing.
