### ISSUE TITLE
Virus detected - Generik.Trojan ?

### ISSUE THREAD

**Issue by Kronix420** [TehCheat/PoEHUD#113]
My personal security suite (ESET Smart Security 2017) detected a virus upon downloading the latest version of x64 -- which has not happened until this version, and/or today. I took it for a false positive, so I isolated the file, un-rar'd it, and scanned again with the same result:

```
<?xml version="1.0" encoding="utf-8" ?>
<ESET>
  <LOG>
    <RECORD>
      <COLUMN NAME="Log">Scan Log</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">Version of virus signature database: 15171 (20170329)</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">Date: 3/29/2017  Time: 7:49:27 PM</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">Scanned disks, folders and files: C:\Users\Admin\Documents\PoEHUD\New folder\PoEHUD-master</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">C:\Users\Admin\Documents\PoEHUD\New folder\PoEHUD-master\PoEHUD-master\PoeHUD.exe - a variant of Generik.JSBUSUN trojan - cleaned by deleting [1]</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">Number of scanned objects: 295</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">Number of threats found: 1</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">Number of cleaned objects: 1</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">Time of completion: 7:49:29 PM  Total scanning time: 2 sec (00:00:02)</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log"></COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">Notes:</COLUMN>
    </RECORD>
    <RECORD>
      <COLUMN NAME="Log">[1] Object has been deleted as it only contained the virus body.</COLUMN>
    </RECORD>
 </LOG>
</ESET>
```

I then decided to run a complete scan of my pc with a different tool; and then proceeded to run a VirusTotal scan to see if other popular scanners would concur, which 31 of 58 did:

[https://www.virustotal.com/en/file/d5dba1f29cd4d54e6d8c81fa743111003776a7955883ef738f27fcbfe446f47e/analysis/1490832963/](url)

I've not personally had an issue with any of the devs in the PoE tool community, and I'm sure this is a false positive as well. All the same, I felt it necessary to inform you that some peoples' AV may throw this detection so we best figure out what the issue is.

Thanks for your time

**Comment by sSmok** [comment]
Chrome blocking the download coz file are dangerous.

**Comment by TehCheat** [comment]
I tested it with Windows Defender and it was flagged as malicious.  I rebuilt the exe and it was fine.  I've since pushed an update to the repository with the new exe file.

Zaafar built that executable, so I have removed him as a collaborator.  All builds will go through me from now on.  I'd also be very hesitant to use any plugins zaafar has created.  No idea if he actually intended to be malicious or not, but this is the first time I've seen so many anti-virus programs throw a fit about HUD and it just happens to be one of the few times I've let someone else push an exe.

**Comment by Kronix420** [comment]
Thank you

**Comment by Treasure-Box** [comment]
Windows defender is garbage please consider using something better such as Nod32, i have also scanned your newly recompiled exe and am getting the same virus flags as his exe on virus total. I really think this is a false positive.

**Comment by Kronix420** [comment]
If virustotal is still giving (false) positives at all, should this not remain open?

**Comment by zaafar** [comment]
Okay, first of all previous one wasn't 31. it was 6.
https://www.virustotal.com/en/file/4c9cfdf1dc9d7ef1a3ad9ec68b1f5456dc14b27558aded0e9e87116128c61135/analysis/

Second of all, current version is showing 1 only.
https://www.virustotal.com/en/file/6eee46a2fdebf6b53d27cb2641820066f8880d293f4ff9f6d3e2425c7c674a6c/analysis/1490967262/


Also @Kronix420 I think your computer is infected by a virus. So 1: format your computer and reinstall the windows. if that's not possible do 2.
2: upload the exe to virus total using a different computer/iphone/mac/laptop/android so it's not infected by some other virus that **may** reside in your system.

I am basing my assumptions on the fact that current version should only show 1 hit but your showing 3 and my (previous) version must show 6 hit and yours showing 31.

**Comment by Kronix420** [comment]
i had virustotal scan the zip only..

**Comment by Kronix420** [comment]
I made an error when I was scanning the file that threw 33 positives, which was in fact POEHUD-Master.zip and was an error on my part. I then moved all testing materials to a seperate folder, and retested every file I have used thus far for this issue, and have found all the same results, except @zaafar 's push only throws 7 positives and not the 30+ that was originally suggested. I would like to personally apologize for this, and state for the record I think this issue should be re-opened and resolved as if the master branch throws 30+ positives then this issue might be a little bit more complicated than @zaafar 's push to the git.

I get 4 positives for the latest version (03/31/2017)
[Virustotal - x64 branch 03/31/2017](https://www.virustotal.com/en/file/f60958d05a9e116fccd8a0d2441dc4b86b067fc2dc5395b51a53da1f3a00dcf8/analysis/)

I get 7 positives from zafaar's push directly prior to the current version (03/28/2017) which has been retested by browsing the git at that particular date, and re-scanning the zip:
[Virustotal - x64 branch 03/28/2017](https://www.virustotal.com/en/file/e713b7daf24ee25d8652bd4119af4a804e704ad132cd0f4896c9d60302dba821/analysis/)

I get 6 positives from 03/25/2017 using the same procedure of browsing back to that day in the git's history, and then downloading and re-scanning the zip
[Virustotal - x64 branch 03/25/2017](https://www.virustotal.com/en/file/485ecdaaffc3a5e45c396a6358a59a44cf76483f982f4a2724006a9bc7726b2f/analysis/)

This brings us back to the day I got the first warning (ever from poehud) regarding this issue. I had been using the version from the 24th (and due to this issue, I still am), and I get no warning from my personal security suite, but just to test, I followed the same procedure and downloaded the zip from that date to test it fresh
[Virustotal - x64 branch 03/24/2017](https://www.virustotal.com/en/file/39309fd2ca2f98346bb8e255f60c5097204ac4783be3d9266fd239ec574538ba/analysis/1491036807/)

This throws the same 6 positives, and thus proves that the (false?) positives stem back further than @zaafar 's push

**Comment by Kronix420** [comment]
We're fairly certain that this is actually a false positive as it's my finding that this has actually been an issue since at least as far back as Master Branch 18/03/2017, and has just not been picked up by any common scanners until the x64 branch update on 28/03/2017. There does not appear to be any malicious activity shown after running this and I have tested the latest version (Apr/02/2017) and I no longer have a warning from ESET Smart Security, or my other tools.

I believe it may be marked as positive simply because it may have a similarity in the naming scripts involved in randomizing the filename that may bear a resemblance to the Generik trojan (or the like). We know that this is simply a security measure used to randomize the name to avoid detection from PoE; and does not in fact have any malicious intent.

Please feel free to do your own testing to make sure, but I am confident that this is a false positive as my personal security suite was what first detected the issue for me on the 28th, and is now not showing any issue with the latest version. I have also done independant testing of the file in question to see if there is any malicious activity after running it and have found no such thing.

If it is showing positive with your personal AV, please post what program it is, and the log associated with the scan and/or a screenshot

**Comment by H4vC** [comment]
I don't think the renaming is triggering a false positive, when I initially implemented and when i2um1 ported it to f# it didn't trigger any AV and I don't think the signature for that bit of code is in any database, alas I'd need to have the executable that triggers a positive to do a more proper analysis.
