### ISSUE TITLE
Ability to quit game when meet certain mod mobs

### ISSUE THREAD

**Issue by RockyBelBoar** [TehCheat/PoEHUD#114]
Hello guys ty in advance for this fantastic tool.
Is possible to add a feature where client quit on login page by using command like:
`cports.exe /close * * * * "PathOfExile.exe"`

Some monsters are impossible to detect intime (like beyond ele/phys reflect or exploding and Flame/Frost/Storm Bearers) cause they have unpredictable spawn.

what about using a player-complied txt like monster_mod_quit.txt ?

cough cough I know poe already didit as alerting but im refer to the cases above.

ty
Alex

**Comment by TehCheat** [comment]
Sounds like an excellent candidate for an external plugin.  Doesn't make sense to be part of the base HUD which is specifically centered around being a heads up display.
