### ISSUE TITLE
Relics

### ISSUE THREAD

**Issue by uLow** [TehCheat/PoEHUD#118]
Is it possible to know is hovered item relic or not?

**Comment by TehCheat** [comment]
Yes, it's possible.

**Comment by uLow** [comment]
Could you provide any additional info?

**Comment by TehCheat** [comment]
This is for issues, not for questions or suggestions.  Perhaps ask better questions in the ownedcore thread and you'll get better answers.

**Comment by uLow** [comment]
In case that nothing in code targets to `relic`, i guess it is issue. And this could be normal `NFR - New Feature Request` that is normal practice for open source. Don't you think so?
