### ISSUE TITLE
Method not found: 'PoeHUD.Poe.Elements.Inventory PoeHUD.Poe.RemoteMemoryObjects.IngameUIElements.get_InventoryPanel()

### ISSUE THREAD

**Issue by Kronix420** [TehCheat/PoEHUD#125]
I am getting an error on the latest version of [Poehud](https://github.com/TehCheat/PoEHUD/tree/c8d1ab08feb1bdeda6739baa6d9891519cdcc850)(04/07/2017)

http://image.prntscr.com/image/c91a90ad4f464dfa87071c6659124e15.png
![c91a90ad4f464dfa87071c6659124e15](https://cloud.githubusercontent.com/assets/647790/24823039/4f084d70-1bc8-11e7-9ef9-49a68ec6b108.png)

This happens with all plugins that have to do with the inventory (item analyzer, inventory preview, and move to stash). It works perfectly fine on the version I was using previous to this on Apr/06/2017 however; which is the only reason I'm posting it here as well as in their respective repos because the only difference is the update on the poehud client.
The log files of each plugin contains the following repeated for as long as the plugin is running. The only difference is the name of the plugin on line 5: 

**_MoveToStash_**
```
Log Entry : 7:00:58 PM Friday, April 7, 2017
 Method error: Render : System.MissingMethodException: Method not found: 'PoeHUD.Poe.Elements.Inventory PoeHUD.Poe.RemoteMemoryObjects.IngameUIElements.get_InventoryPanel()'.
   at MoveToStash.MoveToStash.Render()
   at PoeHUD.Plugins.BasePlugin.iRender()
```

**_InventoryItemsAnalyzer_**
```
Log Entry : 7:00:58 PM Friday, April 7, 2017
 Method error: Render : System.MissingMethodException: Method not found: 'PoeHUD.Poe.Elements.Inventory PoeHUD.Poe.RemoteMemoryObjects.IngameUIElements.get_InventoryPanel()'.
   at InventoryItemsAnalyzer.InventoryItemsAnalyzer.Render()
   at PoeHUD.Plugins.BasePlugin.iRender()

```

**_InventoryPreview_**
```
Log Entry : 7:01:10 PM Friday, April 7, 2017
 Method error: Render : System.MissingMethodException: Method not found: 'PoeHUD.Poe.Elements.Inventory PoeHUD.Poe.RemoteMemoryObjects.IngameUIElements.get_InventoryPanel()'.
   at InventoryPreview.InventoryPreviewPlugin.Render()
   at PoeHUD.Plugins.BasePlugin.iRender()
```
As you can see, the common issue is 
`Method not found: 'PoeHUD.Poe.Elements.Inventory PoeHUD.Poe.RemoteMemoryObjects.IngameUIElements.get_InventoryPanel()`

Is this issue with the plugins, or with poehud itself?

**Comment by TehCheat** [comment]
Yes, changes to HUD can break plugins.  For this specific problem, those plugins will have to adjust.  In the future people will need to be more careful with changes to HUD, being aware of this possibility.  I've pointed it out to the guilty party and I'm sure he'll be more careful in the future.  I'll try to be more careful about the merge requests that I approve.  If it's something that I see will potentially break a plugin, it will be rejected.
