### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by reiluisii** [TehCheat/PoEHUD#128]
Can I bring ban using it?

**Comment by TehCheat** [comment]
It's a 3rd party program that's against the TOS of the game.  Of course you can.

**Comment by reiluisii** [comment]
Has there ever been a ban report?

**Comment by TehCheat** [comment]
People have been banned,  yes.  The only time a lot of people got banned for using HUD was when it contained a map hack years ago.  But people have also gotten banned for resetting instances like crazy farming diviner's stongboxes and the like.
