### ISSUE TITLE
PoeHUD doesnt recognize the x64 Steam Version

### ISSUE THREAD

**Issue by LeagueRaINi** [TehCheat/PoEHUD#133]
`public static Offsets Regular = new Offsets { IgsOffset = 0, IgsDelta = 0, ExeName = "PathOfExile" };`
`public static Offsets Steam = new Offsets { IgsOffset = 0x1C, IgsDelta = -0x4, ExeName = "PathOfExileSteam" };`
Name of the x64 Version: PathOfExile_x64Steam.exe

**Comment by TehCheat** [comment]
Perhaps you should use the x64 branch?

**Comment by LeagueRaINi** [comment]
oh lol, didnt see you have multiple branches, thanks
