### ISSUE TITLE
Drawing via SharpDX

### ISSUE THREAD

**Issue by Scobiform** [TehCheat/PoEHUD#145]
HI there,

I am trying to Draw some things in my Plugin, but whatever I do I get Method error: Render : System.MissingMethodException.

`Graphics.DrawText("Hello World", 15, new Vector2(5F,5F),Color.Red, FontDrawFlags.Center);`

`Method error: Render : System.MissingMethodException: Methode nicht gefunden: "SharpDX.Size2 PoeHUD.Hud.UI.Graphics.DrawText(System.String, Int32, SharpDX.Vector2, SharpDX.Color, SharpDX.Direct3D9.FontDrawFlags)".`

Can you please provide me some information what I am missing. :)

**Comment by vmv** [comment]
new Vector2() it's a position, what is this (5F,5F) ?

**Comment by vmv** [comment]
`Vector2 position = StartDrawPointFunc();`
`Graphics.DrawText("Hello World", 15, new Vector2(position.X + 5, position.Y + 5),Color.Red, FontDrawFlags.Center);`

This should work, try different values until you have the right position.

**Comment by Scobiform** [comment]
Thank you very much, will try that. I am totally new to SharpDX and PoEHud :)

**Comment by Scobiform** [comment]
I am still not able to Draw anything via Plugin... 

This code should be working: 

`float X = GameController.Window.GetWindowRectangle().Width * Settings.PositionX.Value * .01f;
 float Y = GameController.Window.GetWindowRectangle().Height * Settings.PositionY.Value * .01f;

 Vector2 position = new Vector2(X, Y);

Graphics.DrawText("Hello World", 15, new Vector2(position.X + 5, position.Y + 5), Color.Red);`

???

**Comment by zaafar** [comment]
Only reason I can think of ( why it isn't working ) is that you are using wrong version of sharpdx reference. Please use references dll provided in poehud lib folder.

If it still doesn't work, delete the whole folder ( poehud ) and start again. This is a reference issue.

**Comment by zaafar** [comment]
is it resolved??? can we close it?

**Comment by Scobiform** [comment]
All good :) was Ref. Thank you
