### ISSUE TITLE
beta tag /3.0.0

### ISSUE THREAD

**Issue by github23leech** [TehCheat/PoEHUD#148]
The beta client is currently unsupported.

_Couldn't find the file in memory: Data/BaseItemTypes.dat
Try to restart the game._

**Comment by TehCheat** [comment]
The beta client isn't intended to be supported.  To get beta access, donate via the link in the readme.md.

**Comment by github23leech** [comment]
Done!

**Comment by TehCheat** [comment]
Have an ownedcore account I can PM?

**Comment by github23leech** [comment]
owned23leech
