### ISSUE TITLE
error when starting PoEHUD

### ISSUE THREAD

**Issue by viper949** [TehCheat/PoEHUD#150]
I did a little troubleshooting and checked that everything was up to date. I believe it is. Here is the log. If you need anything else please let me know I'll keep this tab open:

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.DllNotFoundException: Unable to load DLL 'd3dx9_43.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>    at SharpDX.Direct3D9.D3DX9.D3DXCreateSprite_(Void* arg0, Void* arg1)
>    at SharpDX.Direct3D9.D3DX9.CreateSprite(Device deviceRef, Sprite spriteOut)
>    at PoeHUD.Hud.UI.Renderers.FontRenderer..ctor(Device device)
>    at PoeHUD.Hud.UI.Graphics..ctor(RenderForm form, Int32 width, Int32 height)
>    at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Comment by TehCheat** [comment]
Download & install the DirectX 9 redistributable.  I actually ran into this recently on a fresh install of Windows 10.

**Comment by viper949** [comment]
ah will do ill let you know

**Comment by viper949** [comment]
that worked ty sir
