### ISSUE TITLE
Cannot inject since 21/07/2017 -- Update to Patch 2.6.3 

### ISSUE THREAD

**Issue by Dragomitch** [TehCheat/PoEHUD#151]
Hi !

I'm not sure if it is only me, but I can't inject the HUD anymore =/ !

**Comment by Aldwew** [comment]
Same here, "Couldn't find the file in memory: Data/BaseItemTypes.dat Try to restart the game."

**Comment by TehCheat** [comment]
Known issue, it is being worked on.  See the ownedcore thread for progress updates.

**Comment by ColdHand** [comment]
Hi! I also do not work because of the release of the new version, can anyone help with this problem?

**Comment by TehCheat** [comment]
See above post.  The more time I waste reading posts rehashing what's already known, the longer it will be before I get it fixed.
