### ISSUE TITLE
main branch not working after the 2.6.3 update.

### ISSUE THREAD

**Issue by TehCheat** [TehCheat/PoEHUD#154]
The main branch (x86) needs offsets updated after the 2.6.3 update.

**Comment by Artieeeee** [comment]
What you think about poe hack space?It's clone x64 version of your cheat witout additionals and with bugs.

**Comment by TehCheat** [comment]
@Artieeeee no idea what poe hack space is.  Also, an issue on the x86 version needing updating is probably not the place to ask about it.  PM me or reply to the HUD thread on ownedcore.

**Comment by TehCheat** [comment]
No longer relevant, as we're way past 2.6.3.
