### ISSUE TITLE
Poehud needs offsets updated for 3.0.

### ISSUE THREAD

**Issue by thedude1987** [TehCheat/PoEHUD#155]
I believe it keeps crashing the health bars keep getting stuck on the screen. Poehud64bit

**Comment by thedude1987** [comment]
Changing from namebar text to % seems to have fixed it for now.

**Comment by TehCheat** [comment]
Yes, offsets aren't yet updated for 3.0.  I'm going to rename your issue title to something more appropriate.  I'll also be updating the ownedcore thread as I fix things.  When it's fully fixed, I'll close this issue.

**Comment by TehCheat** [comment]
OK, most offsets are fixed.  There's still a couple of floating issues (most notably enemy minions and certain mobs showing up as friendly). but it should mostly be working.

**Comment by thedude1987** [comment]
see you replied here. Thanks and sorry for my terminology ;p
