### ISSUE TITLE
Looks like the hud is not working for 3.0

### ISSUE THREAD

**Issue by viper949** [TehCheat/PoEHUD#156]
I assume this might be known before hand but it doesnt look like it is working for 3.0. If this is not known I can tell you exactly what it says.

Also, are there plans to make the HUD work for DX11? Currently is says "Path of Exile is not unning!"

**Comment by TehCheat** [comment]
There's already an issue regarding 3.0.

DirectX 11 is working, go to the main page and select the x64 branch.  Download that and give it a try.  Make sure you have directx 11 selected on the graphics tab in PoE.

**Comment by thedude1987** [comment]
Yo any idea why my character and npcs health bars freeze in place?

**Comment by viper949** [comment]
ah thanks TehCheat
