### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Stimey007** [TehCheat/PoEHUD#161]
"Couldn't find the file in memory:  Data/BaseItemTypes.dat
Try to restart the game"

Is this due to 3.0 launch, and it needs updating, or is there something I should do on my end?  

Thanks mate.

**Comment by zaafar** [comment]
exit the game and retry...
this only happen on rare occasion.

**Comment by exodus863** [comment]
I'm getting the same error

**Comment by zaafar** [comment]
then download the latest version form here
https://github.com/TehCheat/PoEHUD/archive/master.zip

**Comment by Stimey007** [comment]
Same thing.  Been running this over a year and never had this problem.  At first the overlay wouldn't show up a week ago.  Now I get that error every time no matter what I try.  I am using a Radeon R9 280.  Windows 10.  Latest windows update.  All drivers up to date.  I have downloaded the latest version 13 times.  The only thing I can see that is strange is I am getting 3 Application(.exe)  to choose from in the folder.  None of which work.

**Comment by zaafar** [comment]
are you using steam version of the poe or non-steam version???
is your poe settings have directX 11 or directX 9?

**Comment by zaafar** [comment]
if you are using non-steam version of the game with directX11
Add me on discord https://discord.gg/MsSRgfP I will resolve your issue there.

**Comment by Stimey007** [comment]
Non steam.  DX9.

**Comment by Stimey007** [comment]
I can run DX11 if needed.  The instructions say DX9 so that's why I run it.

**Comment by zaafar** [comment]
AH, that's the issue.
Currently POE DX9 isn't updated/supported. Use DX11.
So here's what you need to do. Download poehud from above link that I provided and change the game to DX11. and volla everything will work fine. Good Luck.

Closing the issue.

**Comment by Stimey007** [comment]
Worked like a charm.  Thanks for taking the time to help me. :)
