### ISSUE TITLE
Error Message. 

### ISSUE THREAD

**Issue by BluntTimes** [TehCheat/PoEHUD#165]
I get the error message "Path of Exile isnt running" when i start it up. POE is most certainly up and running. Tried to run it as admin with no success

**Comment by TehCheat** [comment]
You get that message when HUD doesn't see the expected file name running.  You're either running x86 hug with DirectX 11 or x64 HUD with DirectX 9.  Check your settings in PoE, options->Graphics->DirectX Version.  DirectX 9 isn't supported right now (hasn't been updated yet), so change it to DirectX 11 if it isn't already, and then download the latest on the x64 branch on this repo.

**Comment by BluntTimes** [comment]
Thanks for the quick response! but now im getting this message "Couldn't find the file in memory: Data/BaseItemTypes.dat Try to restart the game. "

**Comment by TehCheat** [comment]
I've heard others saying they're getting that, but I am not, so I have no way of troubleshooting it.  That message occurs when the FileRoot pattern/scan doesn't result in HUD finding the files properly.  I have no idea why this would be occurring unless you've got the wrong version of HUD.

**Comment by BluntTimes** [comment]
hmm ive used previous versions but Im pretty sure ive got the right one... ill try and delete all the files and re-download them.

**Comment by BluntTimes** [comment]
That did not work.

**Comment by TehCheat** [comment]
Try restarting HUD/your pc.  I believe this issue is caused when the memory of HUD lines up in an odd way (executable memory after data memory).  Just closing HUD might work, but you can also close HUD and open some other programs causing Windows to juggle the way PoE will be sitting in memory when it's restarted.  That's the theory anyway.

**Comment by exodus863** [comment]
any chance you'll update the 32 bit version? My video card can't support directx 11 :(

**Comment by TehCheat** [comment]
@exodus863  I will when I have time.  Not sure when that will be.

**Comment by zaafar** [comment]
try using this version.
https://github.com/TehCheat/PoEHUD/archive/x64.zip
