### ISSUE TITLE
PoEHUD Garena TW need you!! 3.0.0b

### ISSUE THREAD

**Issue by sam0324sam** [TehCheat/PoEHUD#166]
please~~
I very like your software ,hope it can run in Garena TW

**Comment by zaafar** [comment]
I don't think so there is any chance...unless someone pay me $300 :)

**Comment by TehCheat** [comment]
GarenaTW is usually nearly identical to global version, just a UI offset difference for the garena in game UI element.  Not much else.  I'll try to take a look at some point.

**Comment by flier268** [comment]
Thank you, @TehCheat

**Comment by flier268** [comment]
X64 version can use on GarenaTW,but x86 version(DirectX 9)

**Comment by sam0324sam** [comment]
some features can use,but I can't use all of plugin....
