### ISSUE TITLE
No corrupted Areas shown

### ISSUE THREAD

**Issue by nijet99** [TehCheat/PoEHUD#168]
Hi there

Thanks for the effort. I noticed it doesn't show corrupted areas anymore. Is it possible to readd this feature?

**Comment by TehCheat** [comment]
Where are you looking for corrupted areas?

**Comment by nijet99** [comment]
There's a challenge in Harbinger to kill vaal bosses. I opened like 40 "The Control Blocks" instances and not 1 corrupted area was indicated by the hud. Also I don't recall the Hud having indicated any corrupted area while doing the quests.

**Comment by TehCheat** [comment]
That didn't answer my question at all.  I'll try again, how would you know there's a corrupted area when looking at HUD?

**Comment by zaafar** [comment]
This is going to be fun. *grabs popcorn*

**Comment by nijet99** [comment]
then I ask: Does the hud in any way display corrupted areas upon entering a zone and if so - how?

**Comment by TehCheat** [comment]
Perhaps it's not a bug if you're not sure how it works?

The area name changes colors (to a purple-ish color) when the area has a corrupted side zone.  There's a setting in preload alerts menu to change the corrupted area title on and off, if you turn it off, it will show up as an entry on the preload alerts.

**Comment by zaafar** [comment]
And red = off and white = on.

**Comment by nijet99** [comment]
Perhaps I'm sure how it works and it is a bug.

Incidentally, all the things in the preload alert are turned on and this far, no corrupted area has shown up while leveling 3 chars and encountering several corrupted areas.

**Comment by zaafar** [comment]
That's not possible because hud is notifying me correctly. How about your send a print screen when u see a corrupted area and hud isn't showing anything on top right corner....

**Comment by TehCheat** [comment]
inb4 crickets
