### ISSUE TITLE
The x86 Steam version isn't drawing.

### ISSUE THREAD

**Issue by icediceice** [TehCheat/PoEHUD#176]
There were no error when open POEHUD but nothing get drawn Please see screenshot for more info.

Direct X redist were installed.

This is for x86 version.

![poehud3](https://user-images.githubusercontent.com/31363836/29739157-61e44748-8a61-11e7-936e-ff947f1fe166.png)
![poehud1](https://user-images.githubusercontent.com/31363836/29739156-61e4035a-8a61-11e7-9758-32c4cfe8eda3.png)
![poehud2](https://user-images.githubusercontent.com/31363836/29739158-61e72896-8a61-11e7-8efe-41fbf9763dd4.png)

**Comment by TehCheat** [comment]
Reports like this frustrate me.  x86 is working fine.  The STEAM version of x86 is broken.  I'll take a look.  In the meantime, play the standalone client if you want HUD.

**Comment by icediceice** [comment]
Thanks TehCheat,

It was as you mentioned. Steam version is not working.
