### ISSUE TITLE
3.0.1b x64 DirectX11 unable to launch

### ISSUE THREAD

**Issue by icencoffe** [TehCheat/PoEHUD#177]
- i have Net Framework 4.6.1 installed 
- previous version running fine

screenshot of the error : 
http://i.imgur.com/5ecjNa0.png

**Comment by qqshka** [comment]
Could confirm, same issue, windows 10 btw.

**Comment by zaafar** [comment]
Hmm, I think I missed that dill while making the release.
Let me push an update.

**Comment by zaafar** [comment]
fixed now.
checkout the new version.
closing the issue.
