### ISSUE TITLE
RIP ME cause bug :D

### ISSUE THREAD

**Issue by cudret** [TehCheat/PoEHUD#184]
hey ...u still can click enable/disable plugins even "F12"  menu hide... should be unclickable if is hide...

**Comment by zaafar** [comment]
Oh that’s sucks. Must be due to my last commit.
I will fix this issue as soon as I reach home.

**Comment by zaafar** [comment]
@Stridemann that’s must be because I removed settings.Enable from click event calling.
What should be the solution? Should we use a different list to handle click event for plugins and different one to handle click event of poehud menu?

**Comment by zaafar** [comment]
fixed. download the latest version.
