### ISSUE TITLE
No Pathfinding component?

### ISSUE THREAD

**Issue by mkwhite703** [TehCheat/PoEHUD#190]
when i list components to string, i see a components called pathfinding. was just curious if you were going to add that in any time.

**Comment by zaafar** [comment]
Which entity are you looking for when u find pathfinding component.

**Comment by zaafar** [comment]
And what information are you interested in, from the pathfinding component.

**Comment by mkwhite703** [comment]
well, i'm now more concerned with the FindPatterns function in the memory class. when I scan for an array of bytes using gamecontroller.memory it won't return any values. i know the bytes are there, and my pattern is made correctly. could you assist me with that?

**Comment by mkwhite703** [comment]
if you could even just remote into my machine for me to show you what i'm talking about easier, that'd be great.

**Comment by mkwhite703** [comment]
I really am just trying to find out if the terrain in front of the player is walkable or not

**Comment by mkwhite703** [comment]
hey, sorry. didn't see you Emailed. i am just curious to find if the
terrain in front of the player is walkable. i can find the layout of the
map using cheat engine, but when i try to scan for the byte array with the
memory.FindPatterns function, no address shows up. are you able to help me?

**Comment by mkwhite703** [comment]
please just explain to me how to get the X, Y, and Z of walkable tiles?

**Comment by zaafar** [comment]
Sorry I cannot explain that...it’s not something poehud is made for.

**Comment by mkwhite703** [comment]
does the FindPatterns function only return address that have opcode instructions?

**Comment by TehCheat** [comment]
I'm not really interested in helping someone write a bot.
