### ISSUE TITLE
[Discussion] This program should not be detected, users should not get banned.

### ISSUE THREAD

**Issue by Neph0** [TehCheat/PoEHUD#193]
Hello!

So, I don't get something. It doesn't write to PoE's process memory, so it should be impossible to detect... Either the PoE client lists the active processes and matches them against a hard-coded list (looking for something like `PoEHUD.exe`?), or GGG actively scans the memory of every single process running on the system (which is 100% unlikely), trying to match whatever ways there are to scan the PoE client's memory.

Unless I'm missing something, randomizing the name of the program/registered process every time it's started would make it way harder for GGG to ban anyone using this.

Note that I'm not using the software, I found it in the "Discover repositories" section of Github, and the disclaimer at the top of the readme caught my interest.

**Comment by Neph0** [comment]
The process could also be detected:

* Through a `md5sum` of the process running. Matching md5 = banned. **Solution:** generate the executable on the user's computer, with some random parts, ensuring that every instance of the process has a different md5.
* Checking the executable's location on disk. It could always be in a PoEHUD folder, or something like this. **Solution:** during the installation, have the user pick a folder from his already-existing installations, and randomize the name of all the files used by the software. Generate a shortcut (`.lnk`) that provides every needed file-name. I don't think another program could access shortcut launch options.

**Comment by TehCheat** [comment]
You can also get detected by signature scans on functions. PunkBuster does a lot of this. So a known Aimbot function would have a specific signature, PunkBuster looks for that signature, and if an attached process has that signature... banned.  And GGG has this functionality in their anti-cheat, though I'm not sure they've ever turned it on.

There are ways to mask a function when you build it (insert random nops in functions, change the order of operation in a function, etc.), but if they were to do this, people would get caught. A lot of people.

**Comment by Neph0** [comment]
Note that this is also possible to take a screenshot of any active window (hidden or not) using Windows' API. This one can't be easily bypassed, and regarding the signatures scanning, I guess it's tough to circumvent this one when your project is open source :)
