### ISSUE TITLE
Cant see menu/drawing

### ISSUE THREAD

**Issue by Techtel** [TehCheat/PoEHUD#194]
I use standalone client x64, Directx 11

downloaded the latest x64 PoeHUD version, started both as admin.

No error comes up, both poe and HUD could be started, but ingame i dont see the HUD menu or any drawing at all, just the classic game view as if HUD isnt running at all.

spammed F10 and F12, no success

I got HUD to work on this PC (no hardware changes) like half a year ago, havent played Poe since then, but at least i know how it looks like when HUD is working.

I am really confused, cant post error msg since there is none, anyone have an idea? :(

Thx in advance

**Comment by TehCheat** [comment]
Thanks, but they'll be far more broken in a few hours. I'll wait for the full update to fix all of them at once.
