### ISSUE TITLE
Update PoEHUD for version 3.1.0

### ISSUE THREAD

**Issue by TehCheat** [TehCheat/PoEHUD#195]
Path of Exile has been updated to 3.1.0 and this program needs to be updated to reflect the changes.

**Comment by luckymindzz** [comment]
when this program will be updated ?

**Comment by luckymindzz** [comment]
and autodetonated mine and autoflask :D

**Comment by TehCheat** [comment]
> when this program will be updated ?
As soon as I can after it's patched.

> and autodetonated mine and autoflask :D
If hud is updated properly, those will work when the rest of the program is updated.

**Comment by luckymindzz** [comment]
thanks for reply bro and continue your good work :D

**Comment by Slitchtar** [comment]
getting couldnt find data/baseitemtype.dat like i had awhile back i have redownloaded and relaunched and restarted my computer to no avail.

**Comment by TehCheat** [comment]
Flasks are not working (inventory offsets) and there's something causing a hang.

**Comment by zaafar** [comment]
@TehCheat flasks are working fine now, get the lastest version.

**Comment by osoyoosking** [comment]
i cant find a fix for my screen being all black i see the menu and hud is working but i check my aero is on and transparency is on too aanyone have any ideas win 10

**Comment by luckymindzz** [comment]
need help for auto detonate mine dont work for me

**Comment by osoyoosking** [comment]
ok just wanted you to know i finally fig out what makes poehud black when i load it. took me a while no matter what i did when i loaded poehud everything was black anyhow in the nvidia control panel under manage 3d setting i set my own setting in there well if you change AntiAliasing - FXAA from off to on like i do for alot of game its making poehud black and cant see game..so might want to make a note of it in win 10 needs to be set to off and it work just fine i can see and hud is working great ty guys for your hard work

**Comment by zaafar** [comment]
Cool, there should be an API to check if antialiasing is off or on...we should check that and generate an error msg.
