### ISSUE TITLE
initItem crash

### ISSUE THREAD

**Issue by Hardell** [TehCheat/PoEHUD#20]
In ItemAlertPlugin, line 356:
`string name = GameController.Files.BaseItemTypes.Translate(item.Path).BaseName;`
The Translate function can return a null, in which case the code above throws a NullPointerException and crashes the hud.

When I debugged one of the crashes, the item.Path passed into the Translate function was an empty string, which to me seems like there's another bug somewhere else as well.

**Comment by Hardell** [comment]
Also, when I inspected the EntityWrapper instance from which the item instance came, it said the "isAlive" property was True. I don't know much about the code but it seems like either items are alive or an entity that wasn't an item got into the initItem function.

**Comment by TehCheat** [comment]
Issue is redundant with another, so I'm closing it.
