### ISSUE TITLE
Did not delete file 'PoeHUD.exe" in directory which have [space] in name.

### ISSUE THREAD

**Issue by XaocDIO** [TehCheat/PoEHUD#203]
src\Framework\Tools\scrambler.cs
Change  in `public static bool Scramble(string parameter)`
`Process.Start(dstPath, srcPath);`
on
`Process.Start(dstPath, '"' + srcPath + '"');`

**Comment by ionmike** [comment]
Strange, but we should use verbatim symbol to not lose escaped chars (slashes).
Pseudo code (need to be tested fisrt):
`Process.Start(dstPath, string.Format(@"{0}", srcPath));`
or
`Process.Start(dstPath, $@"{srcPath}"); `

**Comment by zaafar** [comment]
fixed.
