### ISSUE TITLE
sill problem with top left menu

### ISSUE THREAD

**Issue by mega2k0** [TehCheat/PoEHUD#204]
3.1.0b_a still cannot open top left menu

**Comment by Dragomitch** [comment]
Did you tried to open F12 to make it appear ? Or to press it 2 times ?

**Comment by TehCheat** [comment]
My bet is he didn't realize the ≡ symbol is the menu button.

**Comment by mega2k0** [comment]
actually is the mercury trade which  interfere  with the overlay
u lost the bet

**Comment by TehCheat** [comment]
You lost the spelling contest.
