### ISSUE TITLE
Directx 9

### ISSUE THREAD

**Issue by gethonorbro** [TehCheat/PoEHUD#210]
Why is only directx 11 being made on 3.1?

**Comment by TehCheat** [comment]
Because:
A) I don't play DirectX 9.
B) When I update the offsets for DirectX 9 I usually get a tiny amount (if any) in donations and it's simply not worth my time.

**Comment by TehCheat** [comment]
And also, if you look at the OwnedCore thread, I already mentioned I'm working on the offsets for DirectX 9.

**Comment by zaafar** [comment]
closing issue as directX9 isn't supported anymore.

**Comment by gethonorbro** [comment]
You guys are no longer going to support directx 9?

**Comment by TehCheat** [comment]
It's "supported" in that I eventually update the offsets. But nothing more than that.
