### ISSUE TITLE
Map hud overlay is offset from game map

### ISSUE THREAD

**Issue by Anon0112** [TehCheat/PoEHUD#215]
Hi, I'm not sure how this happens but the poehud is offset. My ingame map character icon shows up right where I am, however the monsters that are next to me are shown to the (upper) left of my location on the poehud. This is also true for items and chests and such, and even the little red poehud menu icon is drawn to the upper left of where the actual clickable button is. What is causing this? How do I fix it?

If you look carefully at this screenshot, the monsters are next to my character attacking me, however poehud shows them significantly to my left...
![untitled](https://user-images.githubusercontent.com/34904688/34400187-a36620ae-eb43-11e7-9ece-1f7f528dbd16.jpg)

This has happened to me many times across the different seasons, this is just the first time I'm voicing my issue.

**Comment by TehCheat** [comment]
I've never seen it. Looks like you play in windowed mode, and that's probably where the problem is.

**Comment by Anon0112** [comment]
What? I know you're the creator for the script... but it doesn't work in full screen lol.

Does it? I'm trying it and it doesn't work as an overlay when I'm in fullscreen.

**Comment by TehCheat** [comment]
Windowed fullscreen is a thing, and that's basically all I ever use.

**Comment by Anon0112** [comment]
Ah okay I set it to the same thing and the hud is still offset. I try
refreshing and reopening and restarting poe. I guess if you've never seen
it before we can't do much about it. Am I the only one whose ever had this
issue?

**Comment by zaafar** [comment]
What is your resolution

**Comment by Anon0112** [comment]
Hi zaafar,

Here's a current screenshot of the poehud overlay on the ingame map. The graphics settings are seen in game: 1920x1080 in windowed fullscreen. The poehud is still offset even if I tab to the minimap.
![untitled](https://user-images.githubusercontent.com/34904688/34432095-37787a22-ec29-11e7-9678-33b8a78d07da.jpg)

I figured out how to reproduce it. My current setup is my Dell xps15 laptop connected to my [27" benQ](https://pcmonitors.info/reviews/benq-ew2750zl/) and [24" Dynex](https://www.amazon.com/Dynex-DX-24E150A11-24-inch-1080p-HDTV/dp/B004H1NVYU) 1080p displays via hdmi and usb-C hdmi. When using either external display, the poehud is offset. When I disconnect and play on the laptop screen, poehud works properly.

![untitled](https://user-images.githubusercontent.com/34904688/34432362-58b0c698-ec2b-11e7-9d53-2a5f82f3bcd6.jpg)

**Comment by zaafar** [comment]
don't have two monitors to test and fix this issue.... :(
can't help u much.

**Comment by Cush1337** [comment]
I have always two monitors and have never had any issue with the hud.

Are both your monitors running at different resolutions from each other? I can imagine the offset is due to the HUD being positioned for one resolution but is on a different resolution.

**Comment by Anon0112** [comment]
All three screens are 1920x1080

**Comment by BorringDog14** [comment]
![pud](https://user-images.githubusercontent.com/37023730/36937225-bce5f778-1ed5-11e8-9833-b2f9823c81eb.png)
Red=Where I am on the minimap
Pink=Barrel I am currently pointing to
Orange=Where that barrel is on the minimap
Sorry if its a little confusing but I actually have to scroll that far to be able to see where PoEhud places the markers.

Toubleshooting information
NVIDIA Geforce GTX 970. DirectX 11 version
Game is windowed full screen. Problem continues in every default available resolution.
Problem continues in windowed mode in every possible resolution.
Problem continues through multiple game restarts.
Problem continues through multiple restarts of PoEhud

Dual monitors, both 1920x1080
Tried every font scale availiable, 100%, 125%, 150%, and 175% for both monitors.
Tried several monitor resolutions
Tried game in both monitors
Set other monitor as main and opened game in that one.
Ran PoEhud in administrator.

---

Let me know any other information you need, I'm not amazingly tech oriented but I know how to run DxDiag and basic CMD commands.

**Comment by BorringDog14** [comment]
![image](https://user-images.githubusercontent.com/37023730/36937692-cf2d4c86-1edc-11e8-8962-e2c44c9c3b68.png)
Much clearer picture of how offset the hud is.
