### ISSUE TITLE
Item Tooltips

### ISSUE THREAD

**Issue by asgarothsg** [TehCheat/PoEHUD#216]
I checked https://pathofexile.gamepedia.com/List_of_dex_body_armour_modifiers and cross reference with some armors in game. it seems that some tooltips are not displaying the correct tier for the item.

For instance, for Evasion armor, Virile (maximum life {70-79} ) is displayed as T6 instead of T3.

Correct me if im wrong. Thanks! Keep up the good work.

**Comment by zaafar** [comment]
Virile is actually T6
check here: poeaffix.net
the link you shared haven't been updated since 2016 and is outdated.

**Comment by asgarothsg** [comment]
ahh. thanks man.
