### ISSUE TITLE
refresh rate on mobs, jars, chests and even fps is off. 

### ISSUE THREAD

**Issue by jbirdsitops** [TehCheat/PoEHUD#226]
changed some settings for my graphics card to run the game better and now my hud is acting wild, it crashed twice on me and i cannot seem to get the mob indicator on mini map to "refresh" and run smoothly. for instance. i have monster health bars enabled, as i run thru the map and pass the mobs the health bar cannot be seen, but seconds later i see health bars flying by unsynced to the monsters then reconnecting to them once i stop moving... please help

**Comment by jbirdsitops** [comment]
laggy

**Comment by TehCheat** [comment]
Did you switch to dx9 in poe? If not, I have no idea what settings you changed, see if there's a "load defaults" or something.
