### ISSUE TITLE
Get Entity  — Player mouse hover over target and distance.

### ISSUE THREAD

**Issue by monocraft** [TehCheat/PoEHUD#227]
Is there an option to pull player mouse hover over target and distance?

**Comment by TehCheat** [comment]
I'm not sure what you're asking.

**Comment by monocraft** [comment]
Sorry.  Is there a way to call if user's mouse is hover over a monster?

**Comment by TehCheat** [comment]
I don't think there's a specific function or trigger built into HUD, but it certainly is possible for a plugin to do so with what HUD has.

**Comment by ravand1990** [comment]
There is a "isTargeted" field on Targetable component class

**Comment by TehCheat** [comment]
There is also a pointer that points to hovered entities. I'd imagine that's more along the lines of what he's looking for. Check if there's an entity being hovered over, if there is, check if it's a monster (or a monster that meets your requirements), and then do the stuff you want to do.

**Comment by monocraft** [comment]
isTargeted also means user had their mouse over the monster?

**Comment by TehCheat** [comment]
I believe that's only set to true when the monster is currently being targeted.

**Comment by zaafar** [comment]
U can check hoverUI for mouse hover stuff

**Comment by zaafar** [comment]
Also, join poehud discord channel for more interactive q and a.
