### ISSUE TITLE
f12 menu empty?

### ISSUE THREAD

**Issue by Smeagol001** [TehCheat/PoEHUD#229]
when i hit f12 i only get a tiny red bar on the left and cant seem to figure out how to open or navigate it

**Comment by zaafar** [comment]
Click that tiny red bar.

**Comment by Smeagol001** [comment]
tha doesnt work  idk if it has to do that im using the steam client.....

2018-01-22 2:59 GMT+01:00 Zaafar Ahmed <notifications@github.com>:
