### ISSUE TITLE
hud is closing itself

### ISSUE THREAD

**Issue by Smeagol001** [TehCheat/PoEHUD#234]
ive encountered this now several times 

after some trime playiong the hud just vanishes from the processlist and has to be restarted 
this happens while having the game open for several h and beinng afk in the hideout or city for some time

**Comment by 0houndog0** [comment]
same thing happens to me, even when entering maps, but for me it happens quite often even when being active

**Comment by Smeagol001** [comment]
sometimes it opens itself twice too

**Comment by infintieice** [comment]
Confirmed, often closes the overlay, while the exe continues running.

Cannot seem to isolate it to one sepcific thing happening.  Do not have issue with opening twice.

**Comment by zaafar** [comment]
If u folks can pin point the issue I can try to fix it.

**Comment by 0houndog0** [comment]
For me It happens on entering a map, on a consistent basis

**Comment by zaafar** [comment]
Tested it today, I was afk for hours...enter exit maps a lot...didn’t happened to me. Unless you guys can reproduce it in a deterministic way, I cannot debug/fix it.

**Comment by zaafar** [comment]
Also, look at your poehud error logs for any error.

**Comment by infintieice** [comment]
Where are the logs?

**Comment by zaafar** [comment]
error logs are where the PoeHUD executable is....also each plugins have their own logs where the plugin dll is.

**Comment by 0houndog0** [comment]
what is the exact name of the error log to look for? from the exe directory? i have no plugins installed

**Comment by Smeagol001** [comment]
in trhe prog directory are no logfiles at all
[image: Inline-Bild 1]

2018-02-01 15:46 GMT+01:00 0houndog0 <notifications@github.com>:

**Comment by infintieice** [comment]
I don't have any created logs when it happens to me.  The overlay stops working (doesn't show in PoE), but the exe is still running and the blue x icon is still in the taskbar when this happens, so it's not 'crashing'.  Is there a debug hotkey or some other way to force logs even for non-crash/error?

**Comment by 0houndog0** [comment]
" I don't have any created logs when it happens to me. The overlay stops working (doesn't show in PoE), but the exe is still running and the blue x icon is still in the taskbar when this happens, so it's not 'crashing'
 " 
 same issue, same circumstances

**Comment by zaafar** [comment]
check the latest release, and re-open this issue if the bug is still there.
