### ISSUE TITLE
Bestiary Mobs?

### ISSUE THREAD

**Issue by OperationKD** [TehCheat/PoEHUD#242]
Is there anyway we can see bestiary mobs in the preload overlay?

**Comment by TehCheat** [comment]
Yeah, everyone wants to farm the Saqawine retches, we'll get to it soon enough.

**Comment by OperationKD** [comment]
Ur amazing.

**Comment by TehCheat** [comment]
There's a conversation regarding bestiary detection on the discord channel. I imagine we'll have something useful in the next few hours.

**Comment by OperationKD** [comment]
Im new to github, where can i find the discord?

**Comment by TehCheat** [comment]
Discord is a chat client (like skype). https://discord.gg/ryJhPNg will get you to the channel... I think.

**Comment by faraddox** [comment]
And may be there is possible to display list of rare and unique mobs on current location?
