### ISSUE TITLE
Some stronboxes don't showing on minimap

### ISSUE THREAD

**Issue by faraddox** [TehCheat/PoEHUD#245]
![image](https://user-images.githubusercontent.com/12736024/37176225-e9e7066c-2345-11e8-9ae5-67ddfc8d1ee2.png)
Sometimes stronboxes aren't showing on minimap.

**Comment by TehCheat** [comment]
There was a fix for this. Are you sure you're on the latest code?

**Comment by faraddox** [comment]
Yes, updated few hours ago. But saw this problem again now, no markers on minimap for all stronboxes on this map for example.

**Comment by TehCheat** [comment]
Next time you run across one, humor me by closing HUD, download a fresh copy of HUD into a separate folder, run that version and see if it's displayed or not.

**Comment by faraddox** [comment]
I was running updated version, i cheked files date, it was marth 8. Restarting poehud helps, but some time later i meet stronboxes without map marker again.

**Comment by TehCheat** [comment]
OK, download from here: https://github.com/TehCheat/PoEHUD/archive/x64.zip

Extract to a new folder. Run from new folder\release\poehud.

I don't think you're running the latest just because it has the right date.
