### ISSUE TITLE
Wanna update POEHUD-Garena_X64

### ISSUE THREAD

**Issue by s1495k043** [TehCheat/PoEHUD#247]
please tips me what diffierent between G and X

**Comment by zaafar** [comment]
G is for Garena executable and X is for normal poe game.

**Comment by TehCheat** [comment]
Last I looked the only difference was everything in InGameUIElements is pushed back 0x8 bytes because of a special Garena UI Element.

**Comment by zaafar** [comment]
Can you automate that? Like offsets for steam.....

**Comment by TehCheat** [comment]
Yeah, definitely possible... the bigger problem is they're not always on the same version of the game.

**Comment by zaafar** [comment]
That sucks

**Comment by TehCheat** [comment]
We could always keep a release for the old version hanging around until they actually update.

**Comment by s1495k043** [comment]
One release and make the offset be a config
ps:I update the offset in InGameUIElements.cs and it work fine

**Comment by zaafar** [comment]
Yeah making offsets configuration using a config file would be nice, it would decouple the code from the offsets.

**Comment by zaafar** [comment]
I wonder what would be a good way to do that....

**Comment by s1495k043** [comment]
Reflection and list all public property inherit RemoteMemoryObject
