### ISSUE TITLE
Old menu button.

### ISSUE THREAD

**Issue by faraddox** [TehCheat/PoEHUD#259]
I think there is no reason to use old menu button with new menu. But it is always shown with new version and overlaying first stash tab (i can't choose it now with mouse click, only in tab list or with mouse wheel). Didn't found any config for it to hide.

**Comment by DetectiveSquirrel** [comment]
It will be addressed in the next update

**Comment by zaafar** [comment]
you can turn it off from the new PoeHud menu, click Core -> Show/Hide menu button.
