### ISSUE TITLE
Troubles with loot filter

### ISSUE THREAD

**Issue by faraddox** [TehCheat/PoEHUD#260]
Default item alert is annoying cause it is alerting about too many useless things like gems without quality. I'm using neversink with it and this is result:
![image](https://user-images.githubusercontent.com/12736024/37706870-3ddd1650-2d2b-11e8-97f8-d7ed71b5b14f.png)
Why it is alerting about all things including hided by item filter?
And more, it is showing like these items are most expensive items.

**Comment by DetectiveSquirrel** [comment]
Maybe try checking the forum posts atleast the last 10 pages before you go and make an issue.
https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/644153-poehud-overlay-path-of-exile-updated-3-0-a-post3836632.html#post3836632

**Comment by faraddox** [comment]
Thank you a lot, i'll look here :)

**Comment by TehCheat** [comment]
Duplicate issue. Maybe check existing issues first next time?
