### ISSUE TITLE
April, 1st patch

### ISSUE THREAD

**Issue by faraddox** [TehCheat/PoEHUD#262]
For some reason it doesn't work with new patch. And few times after starting there was some memory leak, about 1.5Gb. Nothing in error.log.

**Comment by faraddox** [comment]
![image](https://user-images.githubusercontent.com/12736024/38168839-82007ce4-357a-11e8-9875-316ac07ba68e.png)
4Gb leak.

**Comment by TehCheat** [comment]
it's out of date, don't run it.

**Comment by faraddox** [comment]
Okay, waiting for update :) Thank you for your work!

**Comment by TehCheat** [comment]
try the latest...

**Comment by faraddox** [comment]
And after server problems - memory leaks again.
