### ISSUE TITLE
Very fast memory leak after few hours of playing

### ISSUE THREAD

**Issue by faraddox** [TehCheat/PoEHUD#263]
With latest version (1.1.5) i had very fast memory leak, freezing all (in previous post - it was leaking without freezes just after start), and after some time poehud closed itself. It happens after 1-2 hours of playing without any issues. Almost died cause i couldn't do anything before it closed. As i can alttab to process explorer, it "eats" from 3 to 5 gb in few seconds.

**Comment by TehCheat** [comment]
What plugins are you using? I get no such issue.

**Comment by faraddox** [comment]
AutoFlaskManager. It is old, but seems work without issues. Newer versions aren't free.
