### ISSUE TITLE
PoEHUD Garena TW need you!! 3.2

### ISSUE THREAD

**Issue by up6gj94ek** [TehCheat/PoEHUD#264]
PoEHUD Garena TW need you!! 3.2

**Comment by lifesucks** [comment]
Please check on the forum, there was an edit on IngameUIElements.cs which have the correct offsets for Garena version, do the edit from the master branch source code and compile yourself

**Comment by a0933974848** [comment]
Try to compile IngameUIElements.cs Still unable to

**Comment by zaafar** [comment]
clsoing this as duplicate. https://github.com/TehCheat/PoEHUD/issues/287
