### ISSUE TITLE
Monster kill counter

### ISSUE THREAD

**Issue by elvese** [TehCheat/PoEHUD#265]
It count killed monsters as a new kills every time you go back to killed enemies. It just adds corpses as kills.

**Comment by elvese** [comment]
Tooo bad i always was curious how many monsters i killed in breach, abyss etc, its really intresting and helpfull, but ok i understand 👍

**Comment by xtenshisanx** [comment]
There is a way to don't double count corpses,  my n sessionstatistic uses that.
