### ISSUE TITLE
i get this everytime, but second launching move out this problemm

### ISSUE THREAD

**Issue by RGBplaya** [TehCheat/PoEHUD#266]
![image](https://user-images.githubusercontent.com/38107216/38371927-539d5bea-38f6-11e8-93f0-d5134f75b821.png)

it says access denied, in russian

**Comment by TehCheat** [comment]
That's a windows error because you don't have permissions to delete it. It could be read only. You probably have another version of it hanging open somewhere.

**Comment by RGBplaya** [comment]
i get this error sometimes actually, sorry. sometimes when i launch poe i dont get, sometimes i get, maybe somehow .exe doesnt delete when i shuttin down my comput?
