### ISSUE TITLE
Argus

### ISSUE THREAD

**Issue by KDENassaj** [TehCheat/PoEHUD#27]
Can add "Argus" boss from Labyrinth to Monster Alert? Like Exiles and other important monsters.

**Comment by vmv** [comment]
Add this line in your preload_alerts.txt file:
Metadata/Monsters/GargoyleBoss/GargoyleBoss; Argus; ffDC143C

**Comment by KDENassaj** [comment]
Thanks you so much!

**Comment by KDENassaj** [comment]
Do you'll add in default preload_alerts.txt in next update?

**Comment by TehCheat** [comment]
I'll add it in.  Thanks vmv!
