### ISSUE TITLE
Change Icon Colour for Essence Worms?

### ISSUE THREAD

**Issue by sjau** [TehCheat/PoEHUD#272]
Hi there

How can I change the icon color for Essence Worms?

**Comment by TehCheat** [comment]
This probably isn't the place to ask that. If you find a bug, create an issue. If you'd like a feature added, join the discord or OC thread and see if someone can help you.

**Comment by sjau** [comment]
what discord or oc thread?

**Comment by TehCheat** [comment]
Discord channel invite: hrYeKFS
Ownedcore thread: https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/644153-poehud-overlay-path-of-exile-updated-3-0-a.html
