### ISSUE TITLE
Hideout - many entries shown

### ISSUE THREAD

**Issue by nijet99** [TehCheat/PoEHUD#275]
For some reason in my hideout all those entries are shown. Becuase I have a small screen it interferes with the stash

https://i.imgur.com/1w2ibsc.png

I don't have any active prophecies.

**Comment by TehHammer** [comment]
Someone entered your hideout with a project and created an instance. You're still in that instance. Let the old hideout expire.

**Comment by TehCheat** [comment]
Hideout was created while prophecies were active. Let it reset and they'll go away.
