### ISSUE TITLE
poehud uses over 30% of my gpu and causes lags - haven't done so before!

### ISSUE THREAD

**Issue by N0oah** [TehCheat/PoEHUD#277]
So i just installed the latest version of the hud ( thanks for your great effort btw ) and suddenly i've encountered huge lagspikes and bad performance all around when i'm using the hud very unlike how it's been for me before. I don't really know why it has come up, which is why i am asking for help here.

I am using a Nvidia GeForce GTX 1060 6GB DDR graphics card and it should be up to the task, which is why i am quite confused. Have you had any experience with this before?
Thanks for the help!

**Comment by TehCheat** [comment]
There was a memory leak, I believe this is fixed now.
