### ISSUE TITLE
How to add new Preload event for testing?

### ISSUE THREAD

**Issue by Anon0112** [TehCheat/PoEHUD#278]
Hi, I wanted to add the following preload line as a test:

![capture](https://user-images.githubusercontent.com/34904688/39846233-6373e290-53af-11e8-9473-854d3ca5edcc.JPG)

I've been searching for days with no luck, so I wanted to test to see if the text will pop up at the appropriate time when it loads into the game. I tried this based on what I thought was the proper format. I don't get a preload alert, and instead get a "Stash tab 10" warning telling me to restart or move my map...

Any help guys?

**Comment by TehCheat** [comment]
It's already in the project.
