### ISSUE TITLE
Uber Hillock

### ISSUE THREAD

**Issue by nijet99** [TehCheat/PoEHUD#279]
I see that there is no indication when Uber Hillock is in The Twilight Strand. Is it possible to add such a notification?

**Comment by TehCheat** [comment]
There is a notification. In release/config/preload_alerts.txt is the following:

```
 # Hillock Event
Metadata/Monsters/ZombieBoss/ZombieBossHillockSpecialEvent_; Uber Hillock; ff00ff00

```

**Comment by nijet99** [comment]
Is that a notification on the area on top like strong boxes? Or is that notification only when you get close to him? Can this be logged to a file?

**Comment by zaafar** [comment]
It’s like strong boxes.

**Comment by nijet99** [comment]
thanks for the reply. Can this be logged to a log file? Basically I'm trying to write a script that will open new instances of The Twilight Strand (rotating through chars) and stop when Uber Hillock was found.

Rotating through chars is easy with AHK but I don't know how to stop when Uber Hillock is there.

**Comment by TehCheat** [comment]
Can it? Yes. Will someone help you? Probably not. We try to avoid bot-ish things because that makes HUD a target.
