### ISSUE TITLE
problème écran noir quand on reviens aux jeux et pour changer revenir aux discorde avec alt tab

### ISSUE THREAD

**Issue by vincentgovaert** [TehCheat/PoEHUD#282]
problème écran noir quand on reviens aux jeux et pour changer revenir aux discorde avec alt tab
                   ![poe hub](https://user-images.githubusercontent.com/33143284/40781477-4cab1dd8-64dc-11e8-8fe4-7718a87546a0.PNG) et après quand je lance le jeux. entent les son du jeux musique j'ai accès a l’interface poe hub aux flask mais pas je vois pas mon personnage car il y a écran noir .      
 mon discorde vincent#6443

**Comment by TehCheat** [comment]
It almost certainly has something to do with your GPU software. Try setting everything to default. My guess is there's some kind of profile switching that's happening that's kicking anti-aliasing control on and killing HUD. But that's just a guess.

Usually when people have this problem it's from the startup of HUD, not after alt-tabbing.

**Comment by vincentgovaert** [comment]
vous prouver pas faire un partages d’écran

**Comment by TehCheat** [comment]
This seems to be limited to you and I can't speak french, so I'm closing the issue.
