### ISSUE TITLE
please make 3.3 poehud

### ISSUE THREAD

**Issue by RGBplaya** [TehCheat/PoEHUD#283]
please make 3.3 poehudplease make 3.3 poehudplease make 3.3 poehudplease make 3.3 poehudplease make 3.3 poehudplease make 3.3 poehudplease make 3.3 poehudplease make 3.3 poehudplease make 3.3 poehud

**Comment by Cush1337** [comment]
poehud works as is right now, do a fresh install and clear plugins.

also poehud is maintained by people in their own free time, begging/spamming is just going to annoy people.

**Comment by TehCheat** [comment]
It was updated before the league even started. Think before you act.
