### ISSUE TITLE
And where is the 'released before the league even started' poehud?

### ISSUE THREAD

**Issue by RGBplaya** [TehCheat/PoEHUD#284]
the latest patch is the 3.2.3c and you said latest poehud is working, open ur eyes LUL. but i can only meet this error when i try to launch this 
![image](https://user-images.githubusercontent.com/38107216/40884910-38f5e34a-6725-11e8-9a59-0305dc46095d.png)

**Comment by zaafar** [comment]
use the latest version.
your version is old.
