### ISSUE TITLE
Incursion League: Stone of Passage

### ISSUE THREAD

**Issue by RighteousHeir** [TehCheat/PoEHUD#285]
I noticed that when one of these drops, it isn't on poehud. Could you please add that item?

**Comment by TehCheat** [comment]
I'll try and get to it in the next day or two.

In the meantime, use an itemfilter that shows them and then load the filter in hud.

**Comment by zaafar** [comment]
Maybe try the latest Neversink filter rather than adding it manually into the poehud.

**Comment by zaafar** [comment]
using latest neversink filter solve this issue.
