### ISSUE TITLE
Tooltips aren't working properly

### ISSUE THREAD

**Issue by TehCheat** [TehCheat/PoEHUD#29]
Mousing over items doesn't always list the proper mods.  DPS Tooltip seems to also be affected by this, not always showing the proper dps.

**Comment by TehCheat** [comment]
Did some null reference checking and this may have fixed this issue.  I'll leave it open until it's been tested more thoroughly.

**Comment by SilentWarrior1** [comment]
seems dps is still the same bugged as before

**Comment by TehCheat** [comment]
Looks like I had an offset wrong.  I check my structure tool and I had it right in there, just missed it when I ported over offsets to HUD.  It should be fixed now, seems to be working.
