### ISSUE TITLE
June 15th update, broken mob radar

### ISSUE THREAD

**Issue by CarryOnMyWayward** [TehCheat/PoEHUD#291]
All mobs now are showing on map in one line, seems like coords are broken or something else. This is first that i saw after today poe update.

**Comment by TehCheat** [comment]
Pretty sure this was already fixed. Click the green Clone or Download button on the main page (https://github.com/TehCheat/PoEHUD).

**Comment by CarryOnMyWayward** [comment]
Thanks a lot. I only checked new releases :)
