### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by pawelgoluba** [TehCheat/PoEHUD#292]
Program exited with message:
 System.TypeLoadException: Nie można załadować typu 'System.Numerics.Vector2' z zestawu 'System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   w PoeHUD.Controllers.GameController.get_UseGameStateController()
   w PoeHUD.Poe.RemoteMemoryObjects.TheGame.get_IngameStateReal()
   w PoeHUD.Poe.RemoteMemoryObjects.TheGame.get_IngameState()
   w PoeHUD.Controllers.StashTabController.CheckCacheStashTabs()
   w PoeHUD.Controllers.StashTabController..ctor()
   w PoeHUD.Controllers.GameController..ctor(Memory memory)
   w PoeHUD.Program.Main(String[] args)

**Comment by TehCheat** [comment]
There are requirements listed in the readme.md file. Install the requirements.
