### ISSUE TITLE
Make 'rename' function optional?

### ISSUE THREAD

**Issue by shot0829** [TehCheat/PoEHUD#293]
the default renaming is causing a lot of issues if there is anti-virus.

**Comment by zaafar** [comment]
Nice try, GGG employee.

**Comment by ravand1990** [comment]
XD

**Comment by TehCheat** [comment]
Whitelist the folder in your antivirus.

**Comment by shot0829** [comment]
really? have you used Bitdefender 2018? there is no way of adding a "folder" in threat defence.
and why on earth should a rename function even be default? you are saying the user are so dumb they cannot rename it them self?

**Comment by shot0829** [comment]
what i do now is simply remove that function and rebuild the whole thing, but what if there are users that are suffering from the same issue and cannot build the code?
why not put on option in the menu that make it not renaming the app next start-up?

**Comment by zaafar** [comment]
the reason why we put that feature by default is so people don’t get ban for using this program.

If we don’t do that, there is a increased chance to get banned from the game.


So either anti-virus complaining or getting banned....you choose...which one is worst.

**Comment by zaafar** [comment]
Byw if you compile the executable locally on your system, antivirus wouldn’t complain ( even after renaming that exe )

**Comment by shot0829** [comment]
well, yes, the reason to put it on default is great. but would it hurt to make on option that turn it off?
If the user decided to turn it off, its their own choice or risk. the user can than decide when ever they want to rename the app. 
And to be honest, if we are really talking about avoiding getting banned, i would suggest adding in MD5 change, which i always do it myself.
what i'm suggesting is having features on as default, but provides the functionality to turn it off if the user desires to.

--------
as for "anti-virus wont complain if self-compiled", that is not the case for Bitdefender 2018. its a little bitch and will detect anything ANYTHING that has malware behavior; and automatically rename and symbolic linking a program is the most typical malware behavior.....

**Comment by ravand1990** [comment]
Well then uninstall your antivirus program if you insist on using it. I don't see the reason to change PoeHUD for the sake of a redundant antivirus program. 

Who the heck uses antivirus programs anyway these days? Haven't used one in 10 years, if you have the slightest idea of what your doing on the internet then you shouldn't need one.

**Comment by shot0829** [comment]
There is no need to be defensive, i'm just providing some suggestions here.
And there is no change to the default behavior, but provides an option.
But if you guys thinks its redundant, no worries.

**Comment by TehCheat** [comment]
A quick Google search suggests whitelisting folders is completely possible, and rather simple, in bitdefender 2018.

**Comment by shot0829** [comment]
well, if you read closely, whitelisting folder is only for "scanning", but not the "threat defense"
these are two functions of bitdefender. (scanning is manual action, while threat defense is passive)
whitelisting a folder in scanning does not prevent threat defense detecting any suspicious actions from apps executed within the folder.
threat defense only allows whitelisting a specific process, which will become invalid every time HUD decided to changes its name automatically.

**Comment by TehCheat** [comment]
I'm aware there are differences between scanning and their automatic scanning, every antivirus has this. Most people are smart enough to figure out how to whitelist in both, but not you, I guess.

**Comment by shot0829** [comment]
there is no where to include a folder in advanced thread defense.....
link the thread if you actually find anything and enlighten me.
yes, i'm aware that most of anti-virus has the ability to add folder in both functions, but bitdefender 2018 doesnt.
Please provide a link or document that acutally show a way to add a "folder" in "advanced threat defense" in "bitdefender 2018". If there is actually one, i'm dumb.

**Comment by zaafar** [comment]
On a separate note “ i would suggest adding in MD5 change“. We do that too.


Let me google bitdefender stuff and post a link for you.

**Comment by zaafar** [comment]
Does this works for you?
https://www.bitdefender.com/consumer/support/answer/2121/

**Comment by shot0829** [comment]
that is for the active scanning only.
the passive is called 'advanced thread defense' in Bitdefender 2018

**Comment by zaafar** [comment]
https://www.bitdefender.com/consumer/support/answer/2393/

Or this

**Comment by shot0829** [comment]
that is the page of 2018 threat defense, yes.
but if we read all steps and the pics, there is no whitelisting folder function.
2018 only allow you to include a specific executable, and the whitelist breaks when PoEHUD changes its name automatically.

**Comment by zaafar** [comment]
Try using *.exe in that folder path.

**Comment by shot0829** [comment]
It doesn't take wildcards.

--------------------------
Well, I have my local solution when rebuilding the repo. 
But in my mind i was thinking: instead of just fixing it for myself, why not suggest this to the team and see if they like it. Turns out most of the team member here doesn't really think my suggestion was anywhere necessary.  

Thanks for the assist anyways.

**Comment by zaafar** [comment]
Thanks for the suggestion but there is a reason we will never do that. Most important thing to us is that we or our users doesn’t get ban. For this rule we have gone great lengths ( e.g. exclude botting features, exclude maphacks, exclude memory writing and stuff from poehud )



I know you wanted it as optional but based on our past experience there are lot of users which are noobs in hacking and stuff like that. If we provide such feature, for one or another stupid reason they will use it and if they get ban they will create hell for us on the form. So it’s either you getting annoyed or them getting annoyed.


I am glad for you that you have a local feature that you can use to mitigate this issue.

Enjoy!


UPDATE: this is not the reason, this is a personal preference we ( poehud developers ) choose to have.

**Comment by TehCheat** [comment]
The last page that zaafar linked says "List of files and folders excluded from scanning". I think you just stop at the folder... i.e. c:\cheats\poehud

You don't specify an exe. You don't put in wildcards. You just put in the folder.

**Comment by shot0829** [comment]
you are looking at the document for scanning, not threat defense.

_____________________

the first link he provides(https://www.bitdefender.com/consumer/support/answer/2121/)
which contain the key word "List of files and folders excluded from scanning" is for scanning. 

---------------------------

the second link he provided (https://www.bitdefender.com/consumer/support/answer/2393/)
is documents for "threat defense", which is the one that causing issue, does not even have a 'folder' keyword init. the app simply would not let you choose a folder.

**Comment by TehCheat** [comment]
I'm looking at the one that has options for both...

**Comment by TehCheat** [comment]
Ah, I see down further on that page. Yeah, looks like you can only specify specific exes there. So yeah, either turn off that part of the antivirus, or remove the function and build manually. We're not removing the auto-rename, we're not adding an option to kill the auto-rename, for all the reasons zaafar mentioned above.
