### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [TehCheat/PoEHUD#303]
[](url)
![2018-07-24_16-49-12](https://user-images.githubusercontent.com/33357938/43130736-86ecef26-8f61-11e8-96ca-9fb559abeac0.png)

x64 steam version

**Comment by Yafar** [comment]
Same problem. Any solution?
Btw. PoeHUD is working with normal version, this is just problem with Steam.

Program exited with message:
 System.ArgumentException: Element o tym samym kluczu został już dodany.
   w System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   w System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   w PoeHUD.Poe.RemoteMemoryObjects.GameStateController.ReadHashMap(Int64 pointer)
   w PoeHUD.Poe.RemoteMemoryObjects.GameStateController..ctor(Memory m, TheGame game)
   w PoeHUD.Controllers.GameController..ctor(Memory memory)
   w PoeHUD.Program.Main(String[] args)
------------------------------

**Comment by TehCheat** [comment]
duplicate of #302
