### ISSUE TITLE
Error after poe updates

### ISSUE THREAD

**Issue by danielwerner-dev** [TehCheat/PoEHUD#304]
26/07/2018 19:31 Program exited with message:
 System.ArgumentException: Já foi adicionado um item com a mesma chave.
   em System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   em System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   em PoeHUD.Poe.RemoteMemoryObjects.GameStateController.ReadHashMap(Int64 pointer)
   em PoeHUD.Poe.RemoteMemoryObjects.GameStateController..ctor(Memory m, TheGame game)
   em PoeHUD.Controllers.GameController..ctor(Memory memory)
   em PoeHUD.Program.Main(String[] args)

**Comment by TehCheat** [comment]
DUPLICATE...

THERE'S ALREADY AN ISSUE FOR THIS. READ FIRST.
