### ISSUE TITLE
3.4.0 PoEHUD is broken and offsets need updating

### ISSUE THREAD

**Issue by TehCheat** [TehCheat/PoEHUD#309]
Offsets need to be updated after the release of 3.4.0.

**Comment by TehCheat** [comment]
IsHostile offset is wrong, which makes minions show up as enemies.

**Comment by zaafar** [comment]
TODO:
		//public bool IsDndEnabled => M.ReadByte(Address + 0xf92) == 1;
		//public string DndMessage => M.ReadStringU(M.ReadLong(Address + 0xf98));

**Comment by zaafar** [comment]
TODO: undo https://github.com/TehCheat/PoEHUD/commit/befbc347c277e5b3159fc0bfc65bce08d497e843#diff-fa0f6c8e671604e0ac4d5fc140c47ea1

**Comment by zaafar** [comment]
TODO: minor fixes to item filter parser



Just making notes for myself. :)
