### ISSUE TITLE
minion are shown as enemy in 3.4.1 patch

### ISSUE THREAD

**Issue by mega2k0** [TehCheat/PoEHUD#314]
they update the game with 3.4.1 last night , minion are shown as enemies

**Comment by ArenaMMORPG** [comment]
For using poehud you will be banned now, why discuss and make new patches about this program??

**Comment by Sirais** [comment]
you are not forced to use it why do you care ?

**Comment by ArenaMMORPG** [comment]
It was the best thing but now its absolutely useless :(

**Comment by zaafar** [comment]
Use limited user method so that you are not detected and can still use it

**Comment by danielwerner-dev** [comment]
zaafar, sorry for asking, but how to run with this method ?

**Comment by zaafar** [comment]
https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/676345-run-poe-limited-user.html
