### ISSUE TITLE
Minions displayed on map even if turned off

### ISSUE THREAD

**Issue by APXEOLOG** [TehCheat/PoEHUD#315]
Minions are displayed on the map and the option to turn it off is not working. I looked at the debug and it seems that "IsHostile" is always true atm, even for minions (checked for golems. skeletons and zombies)

Also, i've heard there is poehud discord somewhere, how do i join it?

**Comment by TehCheat** [comment]
There's already a note that this needs fixed in the general offsets issue that's already open for 3.4.0+.

To get invited to the discord PM me on ownedcore and mention your OC user here so I know it's you and I'll send an invite.
