### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by thedude1987** [TehCheat/PoEHUD#322]
I have windows aero running and am still getting full black screen. Deleting poehud process gets rid of the black screen. Wondering if anyone knows any other fixes.

**Comment by TehCheat** [comment]
You probably have antialiasing forced in nvidia control panel.

**Comment by TehCheat** [comment]
not that it matters much since HUD isn't working currently, but eventually you'll want to see through that, I imagine.

**Comment by thedude1987** [comment]
> 
> 
> You probably have antialiasing forced in nvidia control panel.

Thats what i was about to test when servers went down. Thanks for the quick response sir.
