### ISSUE TITLE
Can you pls add this entity in "monster_mod_alerts.txt"

### ISSUE THREAD

**Issue by RockyBelBoar** [TehCheat/PoEHUD#330]
Hey guys, "monster_mod_alerts.txt" is a good friend for us,
New terrible mobs has been added since his last update
Can you add this entity pls ?

https://pathofexile.gamepedia.com/Modifier:MonsterNemesisLightningCloneLarge

tyvm

**Comment by zaafar** [comment]
is that the one who hit you with the lightening storm?
yeah that's  a bad one...we should add it.

**Comment by RockyBelBoar** [comment]
yes sir :)
tyvm

**Comment by RockyBelBoar** [comment]
found another terrible
https://pathofexile.gamepedia.com/Modifier:MonsterNemesisVines

**Comment by zaafar** [comment]
another one: MonsterNemesisLightningStormDaemon
looks like there is a pattern.
