### ISSUE TITLE
GameStat enums require update for 3.5

### ISSUE THREAD

**Issue by veniversum** [TehCheat/PoEHUD#331]
~400 new stats have been added in 3.5, and the ordering of some keys have been shuffled.

**Comment by zaafar** [comment]
Duplicate issue: https://github.com/TehCheat/PoEHUD/issues/323

**Comment by TehCheat** [comment]
Here's a dump. I wrote a 5 minute plugin to dump it in memory. Side note, these are loaded in game (Stats public variable in FSController) so we really shouldn't be manually dumping them anymore.
https://pastebin.com/N74qL1sX

**Comment by TehCheat** [comment]
https://github.com/TehCheat/StatEnumerator
