### ISSUE TITLE
Crahing + Locking controls in 3.5

### ISSUE THREAD

**Issue by TSM-EVO** [TehCheat/PoEHUD#333]
I'm having a consistent crash in 3.5 

Steps to repro:

Be ingame, with HUD open. 
Select "Exit to Login" or "Exit to Character Selection"
When it logs out, HUD crashes, throwing an error. The problem is that when the error pops up, it's also locking all input. For example, Ctrl Alt Del does not work, the mouse will not move, alt f4 doesn't work. If I use my power button to start the shutdown of my PC, it'll return control after closing the error message. 

I have a bunch of plugins including stashie, basicflask, random features and pickit. Judging by the behaviour on error, it might be one of those plugins, that can block input.

**Comment by TehCheat** [comment]
What version of the game do you play? What DirectX version do you use?

The first step I'd suggest is removing all of your plugins and adding them back in one at a time and seeing which one causes it, because I'm pretty sure one of them is.

**Comment by zaafar** [comment]
Reopen the issue on answering those questions
