### ISSUE TITLE
win10 with complete req still getting error

### ISSUE THREAD

**Issue by xmikaelox** [TehCheat/PoEHUD#338]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'd3dx9_43.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SharpDX.Direct3D9.D3DX9.D3DXCreateSprite_(Void* arg0, Void* arg1)
   at SharpDX.Direct3D9.D3DX9.CreateSprite(Device deviceRef, Sprite spriteOut)
   at PoeHUD.Hud.UI.Renderers.FontRenderer..ctor(Device device)
   at PoeHUD.Hud.UI.Graphics..ctor(RenderForm form, Int32 width, Int32 height)
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
PoeHUD
    Assembly Version: 1.0.6925.14085
    Win32 Version: 1.0.*
    CodeBase: file:///D:/Path%20of%20Exile/PoEHUD-x64/Release/0C9uC.exe
----------------------------------------
SharpDX.Desktop
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///D:/Path%20of%20Exile/PoEHUD-x64/Release/SharpDX.Desktop.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///D:/Path%20of%20Exile/PoEHUD-x64/Release/SharpDX.Mathematics.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
ImGui.NET
    Assembly Version: 0.4.0.0
    Win32 Version: 0.4.0
    CodeBase: file:///D:/Path%20of%20Exile/PoEHUD-x64/Release/ImGui.NET.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
SharpDX
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///D:/Path%20of%20Exile/PoEHUD-x64/Release/SharpDX.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///D:/Path%20of%20Exile/PoEHUD-x64/Release/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SharpDX.Direct3D9
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///D:/Path%20of%20Exile/PoEHUD-x64/Release/SharpDX.Direct3D9.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by zaafar** [comment]
Plz download everything in the requirements page.
https://github.com/TehCheat/PoEHUD/blob/x64/README.md#requirements

**Comment by xmikaelox** [comment]
already did, i have directx11 and win10 installed, couldnt figure out what is causing the error

**Comment by TehCheat** [comment]
directx11? well there's your problem...

**Comment by xmikaelox** [comment]
so its not compatible with directx11 x64bit?
should i just use d9 isntead?

**Comment by TehCheat** [comment]
no, it's compatible with directx 11, it's only compatible with the directx 11 mode in poe (until I fix the dx9 offsets). But it draws with directx 9 which you don't have installed and is listed in the requirements.

This is made obvious by the first line of the error:
`System.DllNotFoundException: Unable to load DLL 'd3dx9_43.dll': The specified module could not be found.`

**Comment by xmikaelox** [comment]
ty so much. this also helped a lot.

https://answers.microsoft.com/en-us/windows/forum/games_windows_10/directx-9-on-windows-10/7b7cec82-4a6d-4bb8-b7a5-3889aae764c1
