### ISSUE TITLE
dots for enemies wrong position?

### ISSUE THREAD

**Issue by ElRatto** [TehCheat/PoEHUD#342]
Hi,
when the map is full screen, the enemies (red/blue..)dots are at their correct position. But when the map is on the top right, the dots are in the right direction but not at the right places.. anyone else has that issue?

**Comment by zaafar** [comment]
Nop.

**Comment by ElRatto** [comment]
ah - was my own fault, i resized the map with +/-

can be closed, it works flawlessly again. Thank you very much
