### ISSUE TITLE
Basic Flask Routine Exception

### ISSUE THREAD

**Issue by username1001101** [TehCheat/PoEHUD#343]
Hi there

I have downloaded newest HUD because on older version I got a basic flask routine exception. However, the exception is still there.

From my little knowledge it seems that a hardcoded path (to your system) was used, since I have a different username and the extraced files lay elsewhere on my system.

![screenshot](https://user-images.githubusercontent.com/39331057/50724511-a780ae80-10ee-11e9-81d0-cf84a07e42e3.png)

**Comment by TehCheat** [comment]
That's hard coded in the flask routine dll, not in HUD.

**Comment by username1001101** [comment]
ah... right... basic flask routine isn't part of the HUD... sorry

**Comment by username1001101** [comment]
Downloaded current version of basic flask manager... now it works.
