### ISSUE TITLE
Offsets for 3.6.0 need updated. If an offset/feature is broken, comment here!

### ISSUE THREAD

**Issue by TehCheat** [TehCheat/PoEHUD#352]

**Comment by izaja** [comment]
09.03.2019 6:27 Program exited with message:
 System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PoeHUD.Framework.Memory.ReadStructsArray[T](Int64 startAddress, Int64 endAddress, Int32 structSize, Int32 maxCountLimit)
   в PoeHUD.Poe.RemoteMemoryObjects.ServerData.GetStashTabs(Int32 offsetBegin, Int32 offsetEnd)
   в PoeHUD.Controllers.StashTabController.CheckCacheStashTabs()
   в PoeHUD.Controllers.StashTabController..ctor()
   в PoeHUD.Controllers.GameController..ctor(Memory memory)
   в PoeHUD.Program.Main(String[] args)

**Comment by ChapaeW** [comment]
09.03.2019 18:05 Program exited with message:
 System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в PoeHUD.Framework.Memory.ReadStructsArray[T](Int64 startAddress, Int64 endAddress, Int32 structSize, Int32 maxCountLimit)
   в PoeHUD.Poe.RemoteMemoryObjects.ServerData.GetStashTabs(Int32 offsetBegin, Int32 offsetEnd)
   в PoeHUD.Controllers.StashTabController.CheckCacheStashTabs()
   в PoeHUD.Controllers.StashTabController..ctor()
   в PoeHUD.Controllers.GameController..ctor(Memory memory)
   в PoeHUD.Program.Main(String[] args)
------------------------------

**Comment by grenuh** [comment]
3/9/2019 1:17 PM Program exited with message:
 System.NullReferenceException: Object reference not set to an instance of an object.
   at PoeHUD.Framework.Memory.ReadStructsArray[T](Int64 startAddress, Int64 endAddress, Int32 structSize, Int32 maxCountLimit)
   at PoeHUD.Poe.RemoteMemoryObjects.ServerData.GetStashTabs(Int32 offsetBegin, Int32 offsetEnd)
   at PoeHUD.Controllers.StashTabController.CheckCacheStashTabs()
   at PoeHUD.Controllers.StashTabController..ctor()
   at PoeHUD.Controllers.GameController..ctor(Memory memory)
   at PoeHUD.Program.Main(String[] args

**Comment by izaja** [comment]
ye, same shit

**Comment by Ganom** [comment]
Enemy health is quite inaccurate ATM

https://i.imgur.com/oV3l0VK.png

**Comment by izaja** [comment]
> ## 09.03.2019 18:05 Program exited with message:
> System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
> в PoeHUD.Framework.Memory.ReadStructsArray[T](Int64 startAddress, Int64 endAddress, Int32 structSize, Int32 maxCountLimit)
> в PoeHUD.Poe.RemoteMemoryObjects.ServerData.GetStashTabs(Int32 offsetBegin, Int32 offsetEnd)
> в PoeHUD.Controllers.StashTabController.CheckCacheStashTabs()
> в PoeHUD.Controllers.StashTabController..ctor()
> в PoeHUD.Controllers.GameController..ctor(Memory memory)
> в PoeHUD.Program.Main(String[] args)

Нашел варик пофиксить?

**Comment by izaja** [comment]
10.03.2019 5:11 Program exited with message:
 

- System.NullReferenceException: Object reference not set to an instance of an object.
-    at PoeHUD.Framework.Memory.ReadStructsArray[T](Int64 startAddress, Int64 endAddress, Int32 structSize, Int32 maxCountLimit)
-    at PoeHUD.Poe.RemoteMemoryObjects.ServerData.GetStashTabs(Int32 offsetBegin, Int32 offsetEnd)
-    at PoeHUD.Controllers.StashTabController.CheckCacheStashTabs()
-    at PoeHUD.Controllers.StashTabController..ctor()
-    at PoeHUD.Controllers.GameController..ctor(Memory memory)
-    at PoeHUD.Program.Main(String[] args)

meh.

**Comment by SadicVicious** [comment]
no one know how to solve?

**Comment by DavidSubZero** [comment]
Same Issue

**Comment by edma0** [comment]
what program you use to check offsets ? reclass ? Id like to help find the offsets but i and unfamiliar with the data structure. 

Im just trying to get Basic Flask Routine , preloads and map icons to work. 

Sorry for being noobie just delete this if it pisses you off.

**Comment by TianqiSu** [comment]
still got broken issue (the comment you deleted) when running poe_x64

and if run poe32, poehud wont work.

**Comment by TehCheat** [comment]
Offsets still need updating. Posting in here is pointless until we have a mostly working version.

**Comment by TianqiSu** [comment]
> Offsets still need updating. Posting in here is pointless until we have a mostly working version.

yeah ik, just wanna provide some help.

**Comment by TehCheat** [comment]
We know they're broken, this isn't helpful.

**Comment by TehCheat** [comment]
* ~~Entitylist isn't quite right. Hitting the limit and throwing a debug message. Needs to be investigated.~~
* FilterParser needs updated with the new keywords.

**Comment by greenbrad** [comment]
Delve plugins is complaining about render index being out of bounds.

**Comment by xzyxzy** [comment]
BasicFlaskRoutine not working.

**Comment by astaentreri** [comment]
Not working:
Stashie https://github.com/nymann/Stashie
Clickit/Pickit https://github.com/DetectiveSquirrel/Pickit
Inventory Item Analyzer (+mods description from base hud) https://github.com/vadash/InventoryItemsAnalyzer
Tradie https://github.com/nymann/Tradie

**Comment by TheOptimisticFactory** [comment]
None of the utility tooltips is showing 
- ~`XP & Area`~
- ~`DPS meter`~
- ~`Map Icons`~

[EDIT on 15/03] Everything is working again 🎉

**Comment by TehCheat** [comment]
They (xp/area) were showing if you had the diagnostic tables (F1) turned off. I fixed the offset that was breaking them, try again. @TheOptimisticFactory

**Comment by Lachrymatory** [comment]
Text element seems to be working sporadically (at least on UI stuff)
E.g. incursion temple map it has text for empty rooms (e.g. pits) but any with an architect inside it is garbled or missing (e.g. Surveyor's Study)

**Comment by astaentreri** [comment]
memory stabilisers show on map as tiny purple chests

**Comment by nymann** [comment]
Everything inside: `GameController.Game.IngameState.ServerData.StashPanel` is not working. Address is 0, and all values are Null/0/False.

**Comment by Qvin0000** [comment]
> Everything inside: `GameController.Game.IngameState.ServerData.StashPanel` is not working. Address is 0, and all values are Null/0/False.

In my stashie version im use this, and i updated all offsets in this element for me all works fine.
PoEHUD/src/Poe/RemoteMemoryObjects/IngameUIElements.cs
public StashElement StashElement => GetObject<StashElement>(0x520);

**Comment by izaja** [comment]
crashes after using blood rage (wtf lol)

**Comment by tvinki899** [comment]
in last hud only in STASHIE plugin dont work popup ( i try change popup bg or hud theme = nothing) 
https://i.imgur.com/kf4t6ym.png

**Comment by TehCheat** [comment]
As was mentioned elsewhere, offsets need updated for the Steam version.

**Comment by Celuni** [comment]
This offset needs to be updated: itemsOnGroundLabelRoot

**Comment by SquirrelRat** [comment]
SyndicatePanel offsets need updating.

**Comment by sychotixdev** [comment]
Looks like IngameUIElements.ChatBox may be broken. Debug plugin shows its address as 7FF7D74F47A0 with all sorts of nonsense other values.

**Comment by Alchemist-VII** [comment]
Offsets to detect owner from items on floor need be updated, cause ClickIt try to pick up items from other players.

**Comment by TehCheat** [comment]
* ~~Steam offsets need updated.~~

**Comment by Lookenpeepers** [comment]
New Map Offset = memory.ReadLong(gameController.Game.IngameState.Data.Address + 0x618);

**Comment by Alchemist-VII** [comment]
~~Offsets about identified items on floor need fix too.~~

**Comment by miuobyshi** [comment]
Betrayal preload broken after last update, show every master

**Comment by TehCheat** [comment]
@miuobyshi Actually that was GGG's "fix" to the stuttering, just load all the assets for all the immortal syndicate members (which is how we get preloads). Except it didn't work. I do think we need to do some cleanup with preloads, though.

**Comment by greenbrad** [comment]
This occurs after the latest update.

![image](https://user-images.githubusercontent.com/22668710/54656231-3882e700-4a9b-11e9-8e77-966836261bf2.png)

**Comment by TehCheat** [comment]
@greenbrad Which plugin is that?

**Comment by greenbrad** [comment]
> @greenbrad Which plugin is that?

It's not a plugin it's your latest update.

**Comment by TehCheat** [comment]
Derp

**Comment by TehCheat** [comment]
I see nothing that's in HUD that has a problem on your screenshot.

**Comment by greenbrad** [comment]
> I see nothing that's in HUD that has a problem on your screenshot.

I'll try a fresh install. Although I just did one. I tried with and without plugins. I'll let you know in the morning.

**Comment by DetectiveSquirrel** [comment]
Thats stashie, you shoud update it maybe..

**Comment by TehCheat** [comment]
lol, "it's not a plugin". It's a plugin.

**Comment by greenbrad** [comment]
> Thats stashie, you shoud update it maybe..



> lol, "it's not a plugin". It's a plugin.

right. that would be great advice if stashie WERE'NT updated. but it is. like i said, i tried with plugins and without plugins. don't know what you didn't understand about that.

**Comment by TehCheat** [comment]
I asked what plugin it was and you said it wasn't a plugin. I'm trying to help, but I can't help if you don't tell me what plugin it is when I ask... And then you say it's not a plugin, when it is... lol

**Comment by DetectiveSquirrel** [comment]
Well, it IS stashie but youre right, you have the most recent version. for some reason the dev enabled the debug portion of code.

https://github.com/nymann/Stashie/commit/b241261db0f0ef6b3cd60db4847c7217af690583

**Comment by greenbrad** [comment]
Oh that isn't obvious at all to people who don't troll every single plugin github. Thanks.

**Comment by DetectiveSquirrel** [comment]
I dont, i just looked to see if there was anything was recently changed on the plugin's github..

**Comment by TehCheat** [comment]
OK so it appears my IsVisible fix fixed the stash dropdown visibility which made that happen. The problem seems to be in Stashie, but only became apparent when HUD got fixed.

**Comment by greenbrad** [comment]
> OK so it appears my IsVisible fix fixed the stash dropdown visibility which made that happen. The problem seems to be in Stashie, but only became apparent when HUD got fixed.

I fixed it and commited it to the master branch of stashie. If anyone wants the update they can download from my fork before he rebuilds and udpates.

**Comment by zaibas** [comment]
don't know if this is b/c of poehud or the plugin itself FullRareSetManager does nothing, and gives following error when stash opened

 Method error: Render : System.NullReferenceException: Object reference not set to an instance of an object.
   at PoeHUD.Poe.Elements.StashElement.GetStashName(Int32 index)
   at FullRareSetManager.Core.UpdateStashes() in C:\Users\Stridemann\Desktop\PoEHUD-x64\src\bin\x64\Debug\plugins\FullRareSetManager\src\FullRareSetManager\Core.cs:line 677
   at FullRareSetManager.Core.Render() in C:\Users\Stridemann\Desktop\PoEHUD-x64\src\bin\x64\Debug\plugins\FullRareSetManager\src\FullRareSetManager\Core.cs:line 105
   at PoeHUD.Plugins.BasePlugin._Render()

**Comment by iargue** [comment]
I think that the latest patch broke the stash offset. Stashie is no longer able to successfully change stash stabs for me.

**Comment by TehCheat** [comment]
I think most of the offsets were fixed a while back. Closing.

Any other specifically missing/broken offsets can be reported individually.
