### ISSUE TITLE
PoEHUD for Garena_TW_X64 3.6 need be updated.

### ISSUE THREAD

**Issue by toadskin** [TehCheat/PoEHUD#361]
Dear friends, PoEHUD for Garena_TW_X64 3.6 need be updated, if you have some free time, please help us update offsets, thank you.

**Comment by repiatx** [comment]
i want to help but i dont know how to find. I could only find Health Mana Energy sheld points.  :/

**Comment by ChapaeW** [comment]
How to turn off sindicat alert ?
![123123123123123](https://user-images.githubusercontent.com/48384261/57978916-28519e80-7a2f-11e9-84cc-482da7d85803.png)
