### ISSUE TITLE
itemalert showing everything

### ISSUE THREAD

**Issue by zaibas** [TehCheat/PoEHUD#371]
itemalert is showing seemingly all items on map as well as the side list, no matter what options i pick or whether i use a filter file
![PathOfExile_x64_2019-03-23_13-54-19](https://user-images.githubusercontent.com/4267174/54870383-c13ba480-4d73-11e9-87df-439bbfec9f96.jpg)

**Comment by Celuni** [comment]
If u dont use a filter file it works after a restart of PoeHUD (exit .exe), not sure about what happens with filter tho, let us know.

**Comment by zaibas** [comment]
works as intended without filter file, tho yea once i load up filter it shows everything again
