### ISSUE TITLE
Item Alert

### ISSUE THREAD

**Issue by username1001101** [TehCheat/PoEHUD#375]
Item Alert doesn't seem to work anymore. It shows every item dropped or almost every item dropped with text and also with drop sound. I'm using as base Neversink's Very Strict filter with few custom additions.

**Comment by TehCheat** [comment]
This is an issue with the new keywords not being handled. As a workaround, I suggest creating a duplicate filter for HUD, and inside of that filter comment out any blocks in the filter that contain HasEnchantment or AnyEnchantment.

It was also an issue with the other new keywords, but we're handling those now.

**Comment by kinkaito** [comment]
Stupid Question, how do you comment out AnyEnchantment?

I've done this:
#------------------------------------
#   [0806] Enchanted Items
#------------------------------------
#
# Show # $type->expl->league
#	AnyEnchantment True
#	SetFontSize 45
#	SetBorderColor 0 240 190 240            # BORDERCOLOR:	 Special Base
#	PlayAlertSound 3 300                    # DROPSOUND:	 Unique
#	PlayEffect Blue
#	MinimapIcon 2 Blue Hexagon

and it's the same

**Comment by TehCheat** [comment]
Made a couple of changes to work around the AnyEnchantment and HasEnchantment keywords. This should no longer spam with invalid alerts.
