### ISSUE TITLE
Poehud KR server need help 

### ISSUE THREAD

**Issue by nienD** [TehCheat/PoEHUD#378]
KR client process name PathOfExile_x64_KG.exe

It is not an independent server.

need help !

**Comment by myso-kr** [comment]
This can be solved using the mklink command.
If new updates are in progress, they can be resolved by applying them.

1. Rename the two executables below.
$ PathOfExile_KG.exe PathOfExile.exe
$ PathOfExile_x64_KG.exe> PathOfExile_x64.exe

2. Run the command prompt with administrator privileges.

3. Use the CD command to navigate to the POE installation path

4. Execute the following two commands.
$ mklink PathOfExile_KG.exe PathOfExile.exe
$ mklink PathOfExile_x64_KG.exe PathOfExile_x64.exe

5. You can now use PoEHUD. enjoy!

**Comment by TehCheat** [comment]
Thanks to the above, I added support for the EXE name, which appears is all it needs.
