### ISSUE TITLE
Help to install....!!

### ISSUE THREAD

**Issue by honhub** [TehCheat/PoEHUD#379]
Hello 
I was an avid user of POEHUD for about 6 months last year. However, I was shit scared to re-use it after the warning message started coming after the tenecent buyout... Although I have played POE very scarcely since then, its no longer fun without seeing those red and blue dots on the map overlay, especially the light blue ones which denote the hidden monsters... 

Can anyone guide me on how to re-use it with the least risk of being banned, as I have spent so many dollars on MTX to lose this account... Thank you...

**Comment by LichProject** [comment]
try this: https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/676345-run-poe-limited-user.html

also, ggg usually can unban you for the first time ban.
