### ISSUE TITLE
An error after update the client

### ISSUE THREAD

**Issue by igorgo** [TehCheat/PoEHUD#38]
13.07.2016 6:10 Program exited with message:
 System.DivideByZeroException: Попытка деления на нуль.
   в PoeHUD.Poe.FileInMemory.<RecordAddresses>d__9.MoveNext()
   в PoeHUD.Poe.FilesInMemory.BaseItemTypes.LoadItemTypes()
   в PoeHUD.Controllers.FsController..ctor(Memory mem)
   в PoeHUD.Controllers.GameController..ctor(Memory memory)
   в PoeHUD.Program.Main(String[] args)
------------------------------

**Comment by TehCheat** [comment]
What version is this in?

**Comment by igorgo** [comment]
garena_ru/2.3.1c

**Comment by TehCheat** [comment]
That's not a version I support.
