### ISSUE TITLE
3.7 Error

### ISSUE THREAD

**Issue by ChapaeW** [TehCheat/PoEHUD#380]
![123](https://user-images.githubusercontent.com/48384261/59144494-66b8f880-89f2-11e9-8168-5a4725bc1a21.png)

**Comment by PoodleJumper** [comment]
same problem here for me 

![](https://i.gyazo.com/f60d8c6d369da1920b44e5e9d0dc5c4e.png)

**Comment by Minescence** [comment]
At least I'm not the only one with this issue.

**Comment by ArenaMMORPG** [comment]
You somehow fixed this??

**Comment by PoodleJumper** [comment]
> You somehow fixed this??

it seemed to be fixed when it was updated.
