### ISSUE TITLE
Help me to fix this

### ISSUE THREAD

**Issue by ArenaMMORPG** [TehCheat/PoEHUD#382]
The 'в' means 'at' 
And 'Данный ключ отсутствует в словаре' means 'The given key was not present in the dictionary.'
![image](https://user-images.githubusercontent.com/38107216/59163251-24351000-8b07-11e9-930d-09c59f69374b.png)

**Comment by LichProject** [comment]
I think that some functions don't support the russian lang of your keyboard, try english layout

**Comment by RGBplaya** [comment]
> I think that some functions doesn't support the russian lang of your keyboard, try english layout

didn't work :(

**Comment by ArenaMMORPG** [comment]
The same problem was closed by 'ChapaeW', if i would look at closed problems, and there will be first closed problem. I tried many things.. :|

**Comment by hnzero001** [comment]
@RGBplaya 
who is 'ChapaeW'

I have the same problem. How did you solve it?

**Comment by hnzero001** [comment]
#382 https://github.com/hnzero001/dream_sky/blob/master/PathOfExile_x64%20bug.PNG
