### ISSUE TITLE
[3.7.2] EntityWrapper.CannotBeDamaged not working

### ISSUE THREAD

**Issue by 0xE0D59** [TehCheat/PoEHUD#387]
3.7.2 broke EntityWrapper.CannotBeDamaged for legion mobs.

https://i.imgur.com/wTLSPSL.png

Curiously, seems to happen to some normal mobs as well.

**Comment by vippotto90** [comment]
item alert problem 
![image](https://user-images.githubusercontent.com/15069975/60326741-88225a00-998a-11e9-9102-d6965cdd4749.png)
