### ISSUE TITLE
Value cannot be null. Parameter Name: Source.

### ISSUE THREAD

**Issue by Laiq91** [TehCheat/PoEHUD#388]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.GroupedEnumerable`3..ctor(IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at PoeHUD.Hud.Loot.ItemAlertPlugin.Render()
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PoeHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
   at PoeHUD.Hud.UI.Graphics.TryRender()
   at PoeHUD.Framework.Helpers.ActionHelper.SafeInvoke(Action action)
   at PoeHUD.Controllers.GameController.WhileLoop()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoeHUD.Hud.ExternalOverlay.<OnLoad>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3801.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
PoeHUD
    Assembly Version: 1.0.7118.1526
    Win32 Version: 1.0.*
    CodeBase: file:///G:/trade/PoEHUD/Release/RFYL41.exe
----------------------------------------
SharpDX.Desktop
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///G:/trade/PoEHUD/Release/SharpDX.Desktop.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3801.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///G:/trade/PoEHUD/Release/SharpDX.Mathematics.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
ImGui.NET
    Assembly Version: 0.4.0.0
    Win32 Version: 0.4.0
    CodeBase: file:///G:/trade/PoEHUD/Release/ImGui.NET.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
SharpDX
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///G:/trade/PoEHUD/Release/SharpDX.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 10.0.3.21018
    CodeBase: file:///G:/trade/PoEHUD/Release/Newtonsoft.Json.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
SharpDX.Direct3D9
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///G:/trade/PoEHUD/Release/SharpDX.Direct3D9.DLL
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 4.1.3.0
    Win32 Version: 4.6.25519.03
    CodeBase: file:///G:/trade/PoEHUD/Release/System.Numerics.Vectors.DLL
----------------------------------------
Antlr4.Runtime
    Assembly Version: 4.6.0.0
    Win32 Version: 4.6.4.0
    CodeBase: file:///G:/trade/PoEHUD/Release/Antlr4.Runtime.DLL
----------------------------------------
PoeFilterParser
    Assembly Version: 1.0.40.0
    Win32 Version: 1.0.40.0
    CodeBase: file:///G:/trade/PoEHUD/Release/PoeFilterParser.DLL
----------------------------------------
Gma.System.MouseKeyHook
    Assembly Version: 5.6.130.0
    Win32 Version: 5.6.130.0
    CodeBase: file:///G:/trade/PoEHUD/Release/Gma.System.MouseKeyHook.DLL
----------------------------------------
Trinet.Core.IO.Ntfs
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.0.0
    CodeBase: file:///G:/trade/PoEHUD/Release/Trinet.Core.IO.Ntfs.DLL
----------------------------------------
BladeFlurryCharges
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.*
    CodeBase: file:///G:/trade/PoEHUD/Release/RFYL41.exe
----------------------------------------
BladeFlurryCharges
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.*
    CodeBase: file:///G:/trade/PoEHUD/Release/RFYL41.exe
----------------------------------------
Random Features
    Assembly Version: 1.0.7105.17573
    Win32 Version: 1.0.*
    CodeBase: file:///G:/trade/PoEHUD/Release/RFYL41.exe
----------------------------------------
Random Features
    Assembly Version: 1.0.7105.17573
    Win32 Version: 1.0.*
    CodeBase: file:///G:/trade/PoEHUD/Release/RFYL41.exe
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by bitternolis** [comment]
the same as you

**Comment by zaafar** [comment]
offsets are broken, they will be fixed soon.
