### ISSUE TITLE
item alert problem

### ISSUE THREAD

**Issue by vippotto90** [TehCheat/PoEHUD#389]
item alert problem 
![image](https://user-images.githubusercontent.com/15069975/60326741-88225a00-998a-11e9-9102-d6965cdd4749.png)

_Originally posted by @vippotto90 in https://github.com/TehCheat/PoEHUD/issues/387#issuecomment-506640361_

**Comment by JoeTheBlow** [comment]
I am getting the same "value cannot be null" error. Crashes almost instantly and PoE Hud is currently not usable.
