### ISSUE TITLE
isValid entity become invalid if distance 1250(before 2500)

### ISSUE THREAD

**Issue by training0112** [TehCheat/PoEHUD#390]
after update today, entity.isvalid have half distance before, it make some plugin like random feature  cant work well, i use developer tool and see that, any entity have distanceFromPlayer > 1250 become invalid

**Comment by zaafar** [comment]
Hmmm

**Comment by zaafar** [comment]
either that or the offset is broken.

**Comment by zaafar** [comment]
@training0112 can you give an example where you saw this behavior? I checked this on my computer and that's not the case...

**Comment by training0112** [comment]
i  use windows 10, checked it on some pc is same result, this happen any where, even in my hideout,  just add debug object and move far  1250 distance, IsValid = false, if i use random feature and press tab, hud just draw all object with distanceFromPlayer < 1250

**Comment by training0112** [comment]
im check it again, now distance increased to 2100, not 1250 like above, may be they have some change?  i dont know but it not like normal, this times i go delve and add delverobot to object nealy
![errror](https://user-images.githubusercontent.com/33222114/60678512-ec737b00-9eae-11e9-9114-5248d4004249.png)

**Comment by training0112** [comment]
exactly this happed with chest in delve mine
![1](https://user-images.githubusercontent.com/33222114/60679179-f302f200-9eb0-11e9-9c93-8306524e611b.png)
in 1000 distance, the Azure chest  still valid, and after move out 1000 range
![2](https://user-images.githubusercontent.com/33222114/60679229-16c63800-9eb1-11e9-89ba-b50191802cb5.png)

**Comment by zaafar** [comment]
In the last patch, GGG nerf delve chests (if that’s your main concern) such that you can’t see it anymore unless you are really close to it (RIP delve plugin).


 If you see this behaviour in anything other than delve chest let me know.

**Comment by ArenaMMORPG** [comment]
always wondered, why can't (and why could not before the nerf) you make very big range so that we even could see far away while delving, and in theory after 80% range nerf we could be able to delve but it would feel like our delving without nerf with default range

**Comment by zaafar** [comment]
Not sure what you mean by “you” over here, you as in ggg or you as in poehud, but as far as I know, all the ranges are server sided meaning poehud can’t control it.

**Comment by TehCheat** [comment]
This is not an issue with PoEHUD but an issue with the network bubble for Delve chests that is out of our control. Closing...
