### ISSUE TITLE
Syndicate  Intervention  preload

### ISSUE THREAD

**Issue by Celuni** [TehCheat/PoEHUD#392]
Hey, the preload for Syndicate Intervention is missing.

**Comment by TehCheat** [comment]
That's because there aren't any files pre-loaded that indicate intervention is in an area.

**Comment by Lachrymatory** [comment]
Jun is preloaded so you can add
`Metadata/Monsters/LeagueBetrayal/MasterNinjaCop; Syndicate Activity; ff00FF00`
To your personal ones and work out which encounters you get by the absence of other preloads.
And obviously if it's only intervention for if you're spamming non-maps or something you only get the above.

**Comment by Celuni** [comment]
Yea I know about that one, I tried to minimize the amount of preloads so I disabled a lot of trash like Abyss, Tormented, etc.
Thanks guys
