### ISSUE TITLE
PoeHUD not working on latest windows update.

### ISSUE THREAD

**Issue by bl4ckm1st** [TehCheat/PoEHUD#393]
Hey TehCheat,

I updated windows yesterday V1903(OS Build 18362.267), to find poehud failing to launch with no error codes, it tries to open but closes immediately.

Love poehud and thanks.

**Comment by bl4ckm1st** [comment]
rolled back to the previous Windows version and it's working again, will pause updates for a while.

**Comment by TehCheat** [comment]
I'm using 1903, and have been for quite some time, and I have no such issue.

**Comment by bl4ckm1st** [comment]
It's working on 1903 but not on OS build 18362.267.

On OS Build 18362.239 it works flawlessly.

**Comment by Bumcha** [comment]
@TehCheat same happened to me, i had to rollback to Windows 10 1903 (OS Build 18362.239) to keep using PoEHUD.

**Comment by TehCheat** [comment]
I had the same problem happen and it turned out to be caused by Riva Tuner Statistics Server. zaafar had the same problem and he had to reset his GPU settings. It's a complex problem that isn't HUD related.
