### ISSUE TITLE
Preload Alert Sounds

### ISSUE THREAD

**Issue by Celuni** [TehCheat/PoEHUD#394]
Is there any chance we add alert sounds to the core preloads plugin upon entering the map just like we have alerts for Unique Exiles?

So we are able to get notified about for example: Unique Chests or Crafting Recipes.

This should be optional and not mandatory for the preloads to work.

I dislike the idea of writing a plugin just for that when we can have it core instead since we have it for monsters alerts already.

**Comment by TehCheat** [comment]
This has been discussed many times and it was never a feature I wanted to implement.
