### ISSUE TITLE
Preloading box is not working properly

### ISSUE THREAD

**Issue by kamilo34843** [TehCheat/PoEHUD#395]
I don't know about you, but I will display 1 in 10 mailboxes - test on mud

ps. do albino preload still work?

![1](https://user-images.githubusercontent.com/54076799/62961716-9a9f0880-bdfd-11e9-9087-ed7fccec15b3.PNG)
![2](https://user-images.githubusercontent.com/54076799/62961717-9a9f0880-bdfd-11e9-9872-dd263e5fe67e.PNG)
![3](https://user-images.githubusercontent.com/54076799/62961718-9a9f0880-bdfd-11e9-9bf1-0853cc063cd6.PNG)
![4](https://user-images.githubusercontent.com/54076799/62961720-9a9f0880-bdfd-11e9-8519-a9b6485df1a5.PNG)
![5](https://user-images.githubusercontent.com/54076799/62961721-9b379f00-bdfd-11e9-95b7-df9bd495b8b3.PNG)
![6](https://user-images.githubusercontent.com/54076799/62961722-9b379f00-bdfd-11e9-98ef-58c2455f3252.PNG)
![7](https://user-images.githubusercontent.com/54076799/62961723-9b379f00-bdfd-11e9-8c3b-dd0882cc42e7.PNG)
![8](https://user-images.githubusercontent.com/54076799/62961724-9b379f00-bdfd-11e9-8e2d-95a69d021948.PNG)
![9](https://user-images.githubusercontent.com/54076799/62961725-9bd03580-bdfd-11e9-83a0-d90afc4ca3b8.PNG)
![10](https://user-images.githubusercontent.com/54076799/62961726-9bd03580-bdfd-11e9-86c8-e8be9049ebe9.PNG)

**Comment by TehCheat** [comment]
GGG broke chest preloads a month or so into Delve to deal with all the chests in Delve. Chests can no longer be preloaded (only when they happen to be within ~2 screens from where you enter the area).

Albino Rhoa should still work fine, since it's not a chest.
