### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Aldwew** [TehCheat/PoEHUD#396]
System.Collections.Generic.KeyNotFoundException: The specified key was not found in the dictionary.
   in System.ThrowHelper.ThrowKeyNotFoundException ()
   in System.Collections.Generic.Dictionary`2.get_Item (TKey key)
   in PoeHUD.Poe.RemoteMemoryObjects.GameStateController..ctor (Memory m, TheGame game)
   in PoeHUD.Controllers.GameController..ctor (Memory memory)
   in PoeHUD.Program.Main (String [] args)

**Comment by Dragomitch** [comment]
At least say something else than juste posting the error ?
Yeah that's because no one took the time to refresh the memory offsets.
You're welcome to do it if you want. In the meanwhile, it will not work before someone take 10 hours free time to do so.
Thanks for the repport anyway

**Comment by vippotto90** [comment]
they need rebuild the exe

**Comment by Aldwew** [comment]
Alright, thanks for the answers
