### ISSUE TITLE
CAn You Continue with update on this software?

### ISSUE THREAD

**Issue by vippotto90** [TehCheat/PoEHUD#397]
we can sen you some money if needed to continue this project(is is that the problem)

**Comment by se7enek** [comment]
problem is that he got banned from poe. not sure if he continues or not after that.

**Comment by TehCheat** [comment]
No, the problem isn't money or being banned, lol. The problem is this version needed A LOT of work. It was horrendously laggy. Qvin already did most of that work and it's much more aesthetically pleasing. Switching to his HUD was the easiest option.
