### ISSUE TITLE
How to find the new offsets?

### ISSUE THREAD

**Issue by frankverreault** [TehCheat/PoEHUD#398]
Hi, 
I just wanted to ask if someone could provide some resources so I can teach myself how to updates those offsets. What programs do you use to find the new offsets?

Thanks in advance!

**Comment by itsC0mrade** [comment]
https://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/644153-poehud-overlay-path-of-exile-updated-3-0-a-post4062585.html#post4062585

**Comment by TehCheat** [comment]
No.
