### ISSUE TITLE
Adding sounds

### ISSUE THREAD

**Issue by xXx9000999xXx** [TehCheat/PoEHUD#41]
I'd like to add a sound effect to a preload alert of strongboxes, can you please explain how to do that?

**Comment by TehCheat** [comment]
This is a feature request, not an issue.  I would like to add the ability to customize sounds, but that's not something that's 'broken' and that's what 'Issues' are for.

**Comment by xXx9000999xXx** [comment]
Sorry, friend. I honestly couldn't find the "PM" button. Anyway, thank you
for supporting this program!
