### ISSUE TITLE
Update 2.4.0f 

### ISSUE THREAD

**Issue by Kronix420** [TehCheat/PoEHUD#42]
The hud worked until the 2.4.0f patch released a few minutes ago. Now not displaying at all.

**Comment by TehCheat** [comment]
In game offset changed.  Next time wait for a release for the current version rather than creating an issue for an out of date version.

**Comment by Kronix420** [comment]
Not asking for a fix  or complaining about it. Im simply stating that the last update didn't affect my hud but this one did. Wanted to make sure you were aware.
