### ISSUE TITLE
PoEHUD needs a version for the TenCent Chinese client

### ISSUE THREAD

**Issue by yege16888** [TehCheat/PoEHUD#48]
First of all thank you very much!
PoEHUD always thought that I was in use, very good!
TW support is also very good
I come from China.
Now China's POE server is on the TX
PoEHUD does not support POE for TX
Hope to support the PoEHUD TX
Http://poe.qq.com/download.shtml
Above is the download address
If you need to test the account I can give you!
Thank you

**Comment by TehCheat** [comment]
I'll take a look at it, but I can't make any promises.  If it's fairly similar, I should be able to add support for it.  If it's very different, it won't be easy for me to do so.

**Comment by yege16888** [comment]
Thank you very much for your reply! Do you need to test this account?
Now TX server needs to test account
If you need to leave a mailbox
I send you my test account!
Your reply and attention is really too much!

**Comment by yege16888** [comment]
China's TX server can support it?
Boss！

**Comment by caxerx** [comment]
It is a lot of different between China server and others. Item binding and auction market added to it. I think it is not easy to modify due to highly inconsistent.

**Comment by yege16888** [comment]
Hope people can study, I think the auction is not the main influence!
After all, the function of HUD does not involve transactions.
The TX version of the HUD version of the last test can be used directly!
If God had time to hope you can study!
I can provide the test account!

**Comment by caxerx** [comment]
I can understand your words. If you had used PoEHUD in Tencent server, it should not be a problem.

**Comment by yege16888** [comment]
I said that the HUD in the last test can be used directly, and now the TX version of the game can not be displayed!
Can be studied under it?
