### ISSUE TITLE
I might be doing something wrong but it seems blank?

### ISSUE THREAD

**Issue by viper949** [TehCheat/PoEHUD#49]
Hello! i just discovered this about a month ago and used it for a couple days until it seemed to go blank. Am I doing something wrong or did the patches mess something up?

**Comment by TehCheat** [comment]
You don't have Aero enabled on your theme.

**Comment by viper949** [comment]
sorry i think i didnt explain correctly its not a BLACK screen I said BLANK like completely transparent with nothing at all on the screen. Is this the same issue as a black screen? If so I looked everywhere for Windows Aero transparency effects and for windows 10 i believe it comes automatically on? The only other info i found was having to go into the regedit

**Comment by TehCheat** [comment]
This would be a better conversation for the ownedcore thread.  This really isn't the place for troubleshooting individual problems when the project is working fine for everyone else.
