### ISSUE TITLE
Health Bars Won't Show

### ISSUE THREAD

**Issue by Stupreme** [TehCheat/PoEHUD#51]
I have enabled health bars for enemy/player but they do not seem to be showing up

**Comment by TehCheat** [comment]
I don't know exactly what is causing this but seeing as how you're the only one who is having the issue, I believe it to be on your end.  Make sure you're running in windowed or windowed full screen.  Make sure Aero is enabled.  If map icons are working, then everything that healthbars rely on is working.  And if that's the case, it's almost certainly a setting in your menu.  Maybe try deleting the settings file in your config folder.
