### ISSUE TITLE
2.4.3 is broken

### ISSUE THREAD

**Issue by Stimey007** [TehCheat/PoEHUD#52]
First off, TehCheat,  Thank you for a great tool.  New to the game and this has helped me to get established.  

After the patch last night, the program does not seem to work.  Is this due to changes in code with the game and PoEHUD requires an update as well to work with the new update?  If so, is this something I should expect when there are patches in the future?  

Again, thank you for your awesome program!  I will be sending some Holiday cheer your way soon. ;)

**Comment by TehCheat** [comment]
Offsets updated for non-steam version on the master branch.

**Comment by Stimey007** [comment]
Awesome!  Thanks man.

**Comment by TehCheat** [comment]
Offsets updated for Steam.  Also drafted a release.  Closing...
