### ISSUE TITLE
Certain aspects not appearing or erroring

### ISSUE THREAD

**Issue by viper949** [TehCheat/PoEHUD#53]
Hello sir I love your work and it is probably the most useful addition to my poe setup yet!

I was wondering if it needs to be updated every time GGG releases a new patch or not because a couple days ago it was working flawlessly after i logged to the login screen and then back into the game.

now a couple day later I am getting several errors and when it doesn't error out it does not show the item location, map enemies, dps, what masters are in the map, etc. am i doing something wrong or do i just need to wait for an update? I'll include pictures and the error logs.

![error ss](https://cloud.githubusercontent.com/assets/16552046/20451526/42dde852-adaf-11e6-917e-12e0736e7dd2.png)
![first error](https://cloud.githubusercontent.com/assets/16552046/20451527/42df1de4-adaf-11e6-8cfc-3d85d3c10bec.png)
[other error.txt](https://github.com/TehCheat/PoEHUD/files/601165/other.error.txt)

**Comment by TehCheat** [comment]
No need to open a duplicate issue.

**Comment by viper949** [comment]
Wtf are you talking about? I fixed the other issue i had weeks ago and this popped up yesterday. Did someone else open a similar issue in the last day or what? 

Like I said I appreciate your work but auto closing my issues without looking at them isn't cool :/

**Comment by viper949** [comment]
Hmm I guess you are talking about the other guy's issue. Well I at least added some logs but if you have everything you need then yay :)

**Comment by TehCheat** [comment]
I looked at your issue.  Next time before opening an issue right after a major update check to see if there's already an open issue for the problem you're having.  There already was one.  Even better, don't open an issue if there's a post on ownedcore.  As soon as there's a post on the HUD thread, I get a notification.  Anything more just wastes my time.

**Comment by viper949** [comment]
My bad I will check that thread
