### ISSUE TITLE
Issue with update 2.4.3

### ISSUE THREAD

**Issue by Kronix420** [TehCheat/PoEHUD#54]
Not working since update 2.4.2

**Comment by TehCheat** [comment]
No need for duplicate issues opened.

**Comment by Kronix420** [comment]
Sorry didnt know the thank you note was an issue :)
Not trying to be a prick -- just making sure you're aware of the patch. Thanks for the great work.

**Comment by TehCheat** [comment]
I honestly don't even want to see issues here when there's an update to PoE that breaks HUD.  I get a notification as soon as there's an update to the ownedcore thread.  I had already made several posts in that thread after the update before this thread was open.  It wastes my time coming here and reading/closing tickets that tell me something I already know.

That said, at least yours has a good title, and is a quick, concise read.  I appreciate that.

**Comment by Kronix420** [comment]
I was actually browsing the several forum threads connected to poehud and couldn't find anything up to date.. My bad though. Again, I totally understand your position and now I can see that yes -- you are right on top of it so it wont be an issue again. Thanks for the amazing support.
