### ISSUE TITLE
64bit DX11 Client is not supported

### ISSUE THREAD

**Issue by emrearapoglu** [TehCheat/PoEHUD#56]
Doesn't detect Path of Exile, throws an error and doesn't run.

Using x64 branch, PoE is running at x64 DX11 mode, Steam version.

**Comment by emrearapoglu** [comment]
I just found out there is a x64 branch :no_mouth:

**Comment by TehCheat** [comment]
This needs pattern scans to work seamlessly.  If I can't find a usable pattern before Breach release, I'll build a separate file with the proper offsets.

**Comment by emrearapoglu** [comment]
It started to work for me after the [commit #36e256d](https://github.com/TehCheat/PoEHUD/commit/36e256d757b6a072a33d45281369d3de9b147144). You may close this if issues are completely solved.

Thanks
