### ISSUE TITLE
Issue with 2.5

### ISSUE THREAD

**Issue by mantas1760** [TehCheat/PoEHUD#57]
Program says that "Path of Exile is not running" tried both non steam and steamed version both doesn't work. :(

**Comment by TehCheat** [comment]
You're probably not using the right version of HUD for the version of PoE that you're using. HUD master branch needs DirectX 9 selected n PoE's options. HUD's x64 branch needs DirectX 11 selected.

**Comment by TehCheat** [comment]
As for Steam, I haven't checked to see if it works, yet.  I'll update my steam PoE today and make sure it is working.

**Comment by TehCheat** [comment]
Tested Steam x64 and x86 and both seemed to be functioning properly.  If there are other issues, it's probably more universal than just a problem with Steam, so I'll close the ticket.
