### ISSUE TITLE
Perandus chest,Cadiro,Corrupted area

### ISSUE THREAD

**Issue by misterhackerbg** [TehCheat/PoEHUD#6]
I play 5 times Weaver chambers Act2 Mercilles,all 5 times i get Perandus chest,two time Cadiro,but POE HUD dont show nothing,its same like to play default,wihout POE HUD.

**Comment by TehCheat** [comment]
These are all working in both the vanilla and steam clients.  I don't support other versions, though I'm happy to include them if others can find the offsets.
