### ISSUE TITLE
About memory address of PoE

### ISSUE THREAD

**Issue by JudyWei** [TehCheat/PoEHUD#60]
Hello,
I'm wonder that if there's any tutorial or tool to get the specified function memory address  without triggering anti-cheat system. I have some coding experience in C# but I'm still want to learn about addressing the software memory. How do you get those memory address like catching the attack damange and hook it as a DPS counter?
It would be a big ask maybe, but still want to know if there's any keyword or any tool to learn the basic, and further.

Thanks!

**Comment by TehCheat** [comment]
This is not an issue, so I'm going to close it.  Message me on ownedcore.com or post a comment on the PoEHUD thread (http://www.ownedcore.com/forums/mmo/path-of-exile/poe-bots-programs/511580-poehud-overlay-updated.html).
