### ISSUE TITLE
Items in list on the right?

### ISSUE THREAD

**Issue by IndianNestingDoll** [TehCheat/PoEHUD#67]
Hi there

I wonder, what do I have to do to show certain items in that item list on the right with the direction indicator?

**Comment by TehCheat** [comment]
There are two ways to do this, the first is by using the files in the config folder (crafting_bases.txt, currency.txt).  The second is by using a filter (by selecting the alternative method in the item alert menu.  The filter parsing doesn't work with a couple of the new keywords (Identified and Corrupted), though.

**Comment by IndianNestingDoll** [comment]
I'm using the custom filter created by Filtration. Some stuff... like currency and uniques are shown.... other stuff is not shown e.g. rares... well, the items appear perfectly on screen (colour, background color, border, size) but not the right-hand side. I can post the filter that I currently use if you want to check

**Comment by TehCheat** [comment]
You have to choose Border and/or sound alert options and the filter has to have a border and/or a sound alert for it to show up.

**Comment by IndianNestingDoll** [comment]
Ah, I just had yellow text for rares. That's why. Thx :)

**Comment by IndianNestingDoll** [comment]
I'm sorry. I added borders for white maps but they won't show up on the right... only rare maps.
