### ISSUE TITLE
PoeHud Crashes my path of exile, also gives weird message

### ISSUE THREAD

**Issue by deatheck** [TehCheat/PoEHUD#68]
Poe hud was working fine, updated to the new one now both poehuds that i have the old version and new are not working. It gives me a message saying that I have to choose an instance to attach to. I've tried yes and no and cancel does nothing. the yes crashes path of exile though. Not sure what the problem is.

**Comment by TehCheat** [comment]
I've only heard of this problem from you, so I assume you have something locally that is causing this.  I can only point you to the readme.md and the first post in the HUD thread on ownedcore, as I have no idea what your setup is.
