### ISSUE TITLE
flasks position changes everytime I use it

### ISSUE THREAD

**Issue by zaafar** [TehCheat/PoEHUD#74]
@Stridemann , @TehCheat  I need a little bit of help from you Guys. Thing is I am getting list of flasks I am equipped by following code

`foreach (Element flaskElem in FlasksRoot.Children)`

I am dependent on the arrangement of flasks in the list ( index 0,1,2,3,4 ) to see which slot the flask have been equipped. but this arrangement changes whenever my FlaskManager drink the flask. Any idea why is this happening.

Is there any better logic to figure out flask slots.

**Comment by TehCheat** [comment]
This isn't part of HUD, so it shouldn't have an issue opened here.
