### ISSUE TITLE
Wiki for PoeHUD's API for Plugins?

### ISSUE THREAD

**Issue by greenbrad** [TehCheat/PoEHUD#81]
TehCheat I don't really know any other way to contact you. I was writing a plugin for PoEHud and looking through PoEHud starts to get kind of cumbersome. 

I was thinking, why is there no wiki with the safe methods to override? But I didn't just want to make one without your permission. So this is me, asking you if you don't mind if I make and maintain a wiki for the purpose of creating plugins for PoEHud?

**Comment by TehCheat** [comment]
PMing on OwnedCore is the best way, as this is rather public.  Or if it's something that isn't necessarily private, the PoEHUD thread on OC is fine, as well.  This should be reserved for actual problems with the HUD, bugs, broken versions, etc.

But to answer your question, yes, that's fine if you do that.
