### ISSUE TITLE
Items in list on the right? No. 2

### ISSUE THREAD

**Issue by IndianNestingDoll** [TehCheat/PoEHUD#86]
Hi,

a little while ago I posted this issue here:

"I wonder, what do I have to do to show certain items in that item list on the right with the direction indicator?"

You said here, that "You have to choose Border and/or sound alert options in HUD and the filter has to have a border and/or a sound alert for a specific item to show up."

However that's not working. In the itemjfilter text I have only this:

```
# Script edited with Filtration - https://github.com/ben-wallis/Filtration
# xxx's Filter

# Maps
Show
    Class "Maps" "Map Fragments"
    SetTextColor 0 0 0
    SetBackgroundColor 184 218 242
    SetBorderColor 255 255 255
    SetFontSize 30
    PlayAlertSound 1 79
```

This filter is loaded in the PoE settings as well as the hud.

You hear the drop sound when the map drops but there's no indicator where the map is and on the HUD you don't see it's location in the map/minimap either.

**Comment by TehCheat** [comment]
I think I recall maps having this problem and the solution was to reference them as "Class Map" rather than "Class Maps".  I could be wrong, though...

**Comment by IndianNestingDoll** [comment]
I'll test :) thx

**Comment by IndianNestingDoll** [comment]
You were right. Altering it to just map works.
