### ISSUE TITLE
Preload not always showing perandus chests

### ISSUE THREAD

**Issue by hakkotsu** [TehCheat/PoEHUD#9]
Spawning at location do not show any chests but after clearing location they eventually show up on the list. Most of the time get this issue with high reward chests (Locker, Safe, Jewellery)

**Comment by vmv** [comment]
I just did few runs in Dried Lake and Jewelry showed up 2 times already. The other chests, do their nature to be more rare, it will take some time to fix them properly.
I will take some time today and see what i can find.
Thanks for reporting this issue.

**Comment by hakkotsu** [comment]
I'm not saying that they are not working at all, but there is definitely some nasty bug. I did over 20 hours of farming runs and it's not just my imagination :)

**Comment by hakkotsu** [comment]
proof
![](http://i.imgur.com/xU5A0op.png)

**Comment by TehCheat** [comment]
I've made a change in the way it checks loaded files.  I've also pushed a new way of parsing the loaded files to the dev branch.  Hopefully this improves the reliability of preloads.

**Comment by TehCheat** [comment]
Also added a check for the generic PerandusChest.ao file which is loaded no matter which chest is in the area.  If it doesn't see a specific box file loaded, but it sees the generic box file loaded, it will give an "Unknown Perandus Chest" alert.
