### ISSUE TITLE
Tiers displaying incorrectly in Item Tooltips

### ISSUE THREAD

**Issue by TSM-EVO** [TehCheat/PoEHUD#97]
I've noticed on a number of different items, tiers are not being displayed correctly.

For example; A belt with +97 Life is showing as a T7 roll in the tooltip. I've also seen it label T2 ES rolls at T10. PoE Trademacro seems to correctly identify the teirs. 

This is an issue because previously, the item tooltip was a good way to identify items with T1-3 rolls. 

This seems to be new in 2.6.

![poehud1](https://cloud.githubusercontent.com/assets/8435204/23774170/8bb5d20a-0576-11e7-923f-1789ac9a7899.png)

**Comment by TehCheat** [comment]
It's getting information directly from the ggpk file, if that is incorrect, then simply ignore it.

**Comment by TSM-EVO** [comment]
Okay cool. This was a great feature ( the coloured highlights for T1 - T2 mods on items when hovering them ) as it makes identifying potentially good items very easy. 

Can I put in a request to have this functionality back in HUD, maybe there's a way to manually list the tiers that's more reliable than the ggpk?
